declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Webpart-Titel (Modus „Nur Inhalt“)",
    LPViewerPropertyDescription: "Benutzerdefinierte Lerneigenschaften",
    LPViewerPropertyGroupName: "Standardansicht",
    WebpartModeLabel: "Webpart-Modus auswählen",
    WebpartModeDescription: "Wie Sie den Webpart anzeigen möchten",
    ShowNavigationLabel: "Kopfzeile der benutzerdefinierten Lernnavigation anzeigen",
    DefaultFilterLabel: "Filter auswählen",
    DefaultFilterDescription: "Wählen Sie einen Filter zum Einschränken der Ergebnisse aus. Sie können immer nur nach einem Typen filtern.",
    DefaultCategoryLabel: "Nach Kategorie filtern",
    DefaultCategoryDescription: "Wählen Sie eine Kategorie aus, um die Ergebnisse einzuschränken.",
    DefaultSubCategoryLabel: "Nach Subkategorie filtern",
    DefaultSubCategoryDescription: "Wählen Sie eine Subkategorie aus, um die Ergebnisse einzuschränken.",
    DefaultPlaylistLabel: "Filtern nach Wiedergabeliste",
    DefaultPlaylistDescription: "Wählen Sie eine Kategorie aus, um die Ergebnisse einzuschränken.",
    DefaultAssetLabel: "Option auswählen",
    DefaultAssetDescription: "Wählen Sie ein Objekt aus, das in der Wiedergabeliste angezeigt werden soll.",
    FilterPanelHeader: "Wählen Sie die Kurse aus, die für Sie am besten geeignet sind.",
    FilterPanelAudienceLabel: "Ich bin",
    FilterPanelSkillsetLabel: "Meine Fähigkeiten sind",
    NavigationHome: "Startseite",
    SearchResultItemPlayListLabel: "Wiedergabeliste: ",
    SearchResultItemCategoryLabel: "Kategorie: ",
    SearchPanelPlaceHolderLabel: "Suchen nach Wiedergabelisten oder Objekten",
    LinkPanelCopyLabel: "Kopie",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Aktuelle Wiedergabeliste: ",
    HeaderPlaylistPanelAdminHeader: "Verwaltung",
    PlaylistOverviewDesignMessage: "Während der Verwendung zeigt dieser Bereich in der Wiedergabeliste, in der er angezeigt wird, andere Objekte an.",
    PlaylistOverviewHeading: "Alle Schritte in Wiedergabeliste",
    BurgerButton: "Burger",
    LinkButton: "Link",
    SearchButton: "Suche",
    AdministerPlaylist: "Wiedergabelistenverwaltung",
    NoSearchResults: "Keine Suchergebnisse stimmten mit Ihrer Abfrage überein.",
    DefaultCDNLabel: "Wählen Sie Lernquelle aus",
    DefaultCDNDescription: "Wählen Sie eine alternative Quelle für Lerninhalte aus.",
    DescriptionFieldLabel: "Beschreibungsfeld",
    ImageSelectorLabel: "Wählen Sie ein Bild aus",
    ImageSelectorButton: "Bild auswählen",
    DetailEditTitle: "Titel",
    DetailEditDescription: "Beschreibung",
    DetailEditUrl: "Url",
    DetailEditCategory: "Kategorie",
    DetailEditCategoryNoData: "Es sind keine Kategorien verfügbar.",
    DetailEditTechnology: "Technologie",
    DetailEditLevel: "Ebene",
    DetailEditAudience: "Zielgruppe",
    AssetSearchPlaceHolderLabel: "Suchen nach vorhandenen Objekten",
    CategoryHeading: "Neue Unterkategorie hinzufügen",
    CategoryHeadingLabel: "Unterkategorie",
    CategoryPlaylistSavedMessage: "Wiedergabeliste wurde gespeichert!",
    CategoryPlaylistSaveFailedMessage: "Wiedergabeliste konnte nicht gespeichert werden!",
    CategoryNewPlayListMessage: "Sie haben Änderungen an einer neuen Wiedergabeliste vorgenommen. Wollen Sie Ihre Änderungen verwerfen und fortfahren?",
    CategoryEditedPlayListMessage: "Sie haben Änderungen an dieser Wiedergabeliste vorgenommen. Wollen Sie Ihre Änderungen verwerfen und fortfahren?",
    PlaylistEditAssetSavedMessage: "Objekt wurde gespeichert!",
    PlaylistEditAssetSaveFailedMessage: "Fehler beim Speichern des Objekts!",
    PlaylistEditCreatePlaylistHeader: "Erstellen einer neuen Wiedergabeliste",
    PlaylistEditPlaylistDetailsHeader: "Details zur Wiedergabeliste: ",
    PlaylistEditPlaylistAssetsHeader: "Objekte der Wiedergabeliste",
    PlaylistEditEditLabel: "Detail bearbeiten",
    PlaylistEditSaveLabel: "Detail speichern",
    PlaylistEditCancelLabel: "Details abbrechen",
    PlaylistEditCloseLabel: "Wiedergabeliste schließen",
    AssetDetailsCreateHeader: "Erstellen eines neuen Objekts",
    AssetDetailsManageHeader: "Benutzerdefiniertes Objekt verwalten:",
    AssetDetailsDetailsHeader: "Objektdetails: ",
    AssetDetailsSaveLabel: "Objekt speichern",
    AssetDetailsCancelLabel: "Objekt stornieren",
    AssetDetailsCloseLabel: "Objekt schließen",
    AssetDetailsOpenPage: "Seite öffnen",
    TechnologyHeadingLabel: "Technologie",
    SubcategoryHeadingLabel: "Unterkategorienüberschrift",
    PlaylistItemPlaylistHeadingLabel: "Wiedergabeliste",
    PlaylistItemPlaylistDelete: "Wiedergabeliste löschen",
    PlaylistEditAssetNewLabel: "Neues Objekt",
    PlaylistRemove: "Aus Wiedergabeliste entfernen",
    ImageSelectorImageAlt: "Benutzerdefinierte Wiedergabeliste",
    ImageSelectorUrlPlaceholder: "Bild-URL",
    CategoryHeadingAddPlaylistToSubcategory: "Neue Wiedergabeliste zu Unterkategorie hinzufügen",
    AdminMenuTechnologyLabel: "Technologie",
    AdminMenuCategoryLabel: "Kategorie",
    Show: "Anzeigen",
    Hide: "Ausblenden",
    Add: "Hinzufügen",
    Edit: "Bearbeiten",
    CloseButton: "Schließen",
    EditButton: "Bearbeiten",
    StepButton: "Schritt",
    MoveUpButton: "Nach oben",
    MoveDownButton: "Nach unten",
    SaveButton: "Speichern",
    CancelButton: "Abbrechen",
    UpdateButton: "Update",
    DeleteButton: "Löschen",
    DetailEditNewPageMessage: "Neue Objektseite in der Siteseitenbibliothek.",
    DetailEditExistingPageMessage: "Geben Sie die URL einer vorhandenen Seite ein.",
    DetailEditNewPageButton: "Objektseite erstellen",
    DetailEditExistingPageButton: "URL eingeben",
    AdminAddCdnLabel: "Inhaltspaket hinzufügen",
    AdminEditCdnLabel: "Inhaltspaket bearbeiten",
    AdminDeleteCdnLabel: "Inhaltspaket löschen",
    AdminCdnIdLabel: "Inhaltspaket-ID/Partner-ID",
    AdminCdnDisplayName: "Anzeigename",
    AdminCdnBaseUrl: "Basis-URL",
    AdminCustomCdnTitle: "Benutzerdefiniertes Inhaltspaket",
    AdminCustomCdnDescription: "Benutzerdefinierte Inhaltspakete sind eine erweiterte Funktion und sollten nur von Administratoren mit Erfahrung in der Verwaltung von Webinhalten verwendet werden. Nicht vertrauenswürdige Inhaltsquellen können unsichere Inhalte in Ihre Website einbringen. Sie sollten nur Quellen hinzufügen, denen Sie vertrauen. Weitere Informationen finden Sie unter „Partneranleitung“ in der Dokumentation zu den Lernpfaden.",
    AdminConfirmContentPack: "Es wurde eine neue Browserregisterkarte mit der Möglichkeit zur Bereitstellung des neuen Inhaltspakets gestartet. Wenn Sie dies erfolgreich abgeschlossen haben, klicken Sie unten auf \"Fertigstellen\", um die Liste der alternativen Inhalte zu aktualisieren. Wenn Sie eine Fehlermeldung erhalten oder das Inhaltspaket nicht installieren möchten, klicken Sie auf \"Abbrechen\". Sie können jederzeit wieder zurückkehren.",
    AdminCdnCompleteButton: "Abschließen",
    AdminCdnCancelButton: "Abbrechen",
    AdminCdnSaveButton: "Speichern",
    AdminCdnUpdateButton: "Update",
    AdminRemoveCdn: "Bestätigen Sie, dass Sie das ausgewählte CDN entfernen möchten?",
    AdminAbout: "Über Webpart",
    DocumentationLinkLabel: "Dokumentation der M365-Lernpfade öffnen",
    CategoryCopyPlaylistFail: "Wenn das Kopieren der Wiedergabeliste fehlgeschlagen ist, wenden Sie sich bitte an den Administrator, oder sehen Sie in der Browserkonsole nach, um weitere Einzelheiten zu erfahren.",
    PlaylistEditCopyLabel: "Wiedergabeliste kopieren",
    PlaylistNext: "Weiter",
    PlaylistPrevious: "Zurück",
    PlaylistFullScreen: "Aktivieren des Vollbildmodus",
    FilterNotSet: "Alle",
    AdminVersionUpdateNotice: "Ihr installiertes Microsoft 365-Lernpfad-Webpart ist veraltet. Die Version %0% wird aktuell ausgeführt, und die neueste Version ist %1%.",
    AdminVersionUpdateInstructions: "Lesen Sie die Anweisungen zum „Aktualisieren der Lösung“.",
    AdminSecurityMessage: "Sie verfügen nicht über die Rechte zum Verwalten von Microsoft 365-Lernpfaden. Bitte wenden Sie sich an den Administrator, um der Besitzer- oder Mitgliedergruppe beizutreten.",
    AdminConfigIssueMessage: "Microsoft 365-Lernpfade weisen ein Konfigurationsproblem auf. Bitten Sie Ihren Administrator um Hilfe. [Administratoren: Detaillierte Protokolle finden Sie in der Browserkonsole. Für technische Unterstützung sehen Sie sich die Liste der Probleme unter „https://github.com/pnp/custom-learning-office-365/issues“ an.]",
    AdminAwaitingUrlPrompt: "Url: Warten auf Titel...",
    CreatingPage: "Seite wird erstellt",
    TryAgain: "Versuchen Sie es erneut",
    AddLanguagePlaceholder: "Sprache hinzufügen",
    NotApplicable: "Nicht zutreffend",
    DataUpgradeTitle: "Datenupgrade von",
    DataUpgradeIntro: "Sie haben auf eine wichtige neue Version von Microsoft 365-Lernpfade aktualisiert. Drücken Sie \"Start\", um mit dem Aktualisierungsvorgang zu beginnen.",
    DataUpgradeStart: "Starten",
    DataUpgradeClose: "Schließen",
    DataUpgradeIssue: "Wenn Sie bei der Durchführung des Updates auf Probleme stoßen, können Sie Unterstützung anfordern, indem Sie ein Problem an die  ",
    DataUpgradeIssueLink: "GitHub-Problemliste für Microsoft 365-Lernpfade melden.",
    DataUpgradeLog: "Upgradeprotokoll",
    DataUpgradeComplete: "Das Upgrade wurde abgeschlossen.",
    DataUpgradeErrors: "Fehler",
    LogLevel: "Ebene",
    LogMessage: "Nachricht",
    AboutGroupHeader: "M365-Lernpfade",
    AboutGroupTitle: "Aktuelle Konfiguration*",
    AboutGroupTitle2: "(* wird spezifisch für das aktuelle Inhaltspaket sein)",
    AboutLearningSiteUrl: "URL der Lernsite:",
    AboutBaseCDNPath: "Basis-CDN-Pfad:",
    AboutTelemetryStatus: "Telemetriestatus:",
    AboutCurrentWPVersion: "Aktuelle Webpartversion:",
    AboutMultilingualEnabled: "Mehrsprachige Seiten aktiviert:",
    AboutMultilingualLanguages: "Mehrsprachige Seiten – Übersetzungssprachen:",
    AboutConfiguredLanguages: "Konfigurierte Sprachen:",
    AboutSupportedLanguages: "Vom Inhaltspaket unterstützte Sprachen:",
    AboutDefaultSiteLanguage: "Standardsprache für die Website:",
    AboutCurrentUserLanguage: "Aktuelle Benutzersprache:",
    AboutContentPackAssetOrigins: "Herkunft des Inhaltspaketobjekts:",
    AboutCurrentCDN: "Aktuelles CDN:",
    AboutAllCDNs: "Alle CDNs:",
    AboutCacheLastUpdate: "Cache letztes Update:",
    DocumentLibraries: "Dokumentbibliotheken",
    OpenButtonLabel: "Öffnen",
    CancelButtonLabel: "Abbrechen",
    UploadFileHeader: "Datei hochladen",
    ChangeFileLinkLabel: "Datei ändern",
    ChooseFileLinkLabel: "Datei auswählen",
    AddFileButtonLabel: "Datei hinzufügen",
    WebSearchLinkLabel: "Websuche",
    CreativeCommonsMessage: "Diese Ergebnisse werden mit Creative Commons-Lizenzen getaggt. Überprüfen Sie die Lizenzen, um sicherzustellen, dass Sie diese einhalten.",
    CopyrightWarning: "Sie sind dafür verantwortlich, die Rechte anderer zu respektieren, einschließlich des Urheberrechts.",
    CopyrightUrl: "https://www.microsoft.com/de-de/legal/copyright/default.aspx",
    LearnMoreLink: "Erfahren Sie mehr.",
    NoResultsBadEnglish: "***Es wurde kein Ergebnis gefunden. Versuchen Sie, die Filteroptionen zu ändern",
    SearchResultAlt: "Bildergebnis für {0}.",
    SearchResultAriaLabel: "Drücken Sie die EINGABETASTE, um die Bildquelle in einer neuen Registerkarte zu öffnen.",
    SearchBoxPlaceholder: "Websuche",
    PoweredByBing: "Unterstützt von Bing",
    SizeOptionAll: "Alle",
    SizeOptionExtraLarge: "Sehr groß",
    SizeOptionLarge: "Groß",
    SizeOptionMedium: "Mittel",
    SizeOptionSmall: "Klein",
    LayoutOptionAll: "Alle",
    LayoutOptionSquare: "Quadrat",
    LayoutOptionTall: "Hoch",
    LayoutOptionWide: "Breit",
    LicenseOptionAll: "Alle",
    LicenseOptionAny: "Nur Creative Commons",
    RecentDocumentsHeader: "Zuletzt verwendete Dokumente",
    Loading: "Wird geladen...",
    NoRecentFiles: "Keine zuletzt verwendeten Dateien",
    NoRecentFilesDescription: "Versuchen Sie, eine Datei von Ihrer Website auszuwählen oder von Ihrem Gerät hochzuladen.",
    EditedByNamePlate: "Bearbeitet von ",
    LinkHeader: "Über einen Link",
    LinkFileInstructions: "Fügen Sie einen Link zu einer Datei in OneDrive for Business oder SharePoint Online ein",
    NoExternalLinksValidationMessage: "Wir unterstützen nur die Verknüpfung mit Dateien in Ihrer eigenen Organisation.",
    ProvidedValueIsInvalid: "Der bereitgestellte Wert ist ungültig.",
    ImageAriaLabelTemplate: ".{0} Bild",
    DocumentLabelTemplate: "{0}, Dokument, Geändert {1}, bearbeitet von {2}, Privat",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, Ordner, Geändert {1}, bearbeitet von {2}, {3} Elemente, Privat",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 Byte",
    SizeUnit: [
      "Bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Dateiauswahl",
    OrgAssetsTabLabel: "Bilder und Dateien, die von Ihrer Organisation bereitgestellt werden",
    RecentLinkLabel: "Zuletzt verwendet",
    SiteLinkLabel: "Website",
    UploadLinkLabel: "Hochladen",
    FromLinkLinkLabel: "Über einen Link",
    TypeAriaLabel: "Spaltenvorgänge für Dateityp: zum Sortieren nach Dateityp drücken",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Ordner",
    ImageAltText: ".{0} Bild",
    NameField: "Name",
    SortedAscending: "Sortiert von A bis Z",
    SortedDescending: "Sortieren von Z bis A",
    ModifiedField: "Änderungsdatum",
    ModifiedByField: "Geändert von",
    FileSizeField: "Dateigröße",
    OneDriveEmptyFolderAlt: "Leerer Ordner",
    OneDriveEmptyFolderDescription: "Wenn Sie Dateien hinzufügen möchten, wechseln Sie zu Ihrem OneDrive. Sie können diesem Ordner Dateien auch mithilfe der OneDrive-App für Ihren Computer hinzufügen.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Dieser Ordner ist leer.",
    ListLayoutAriaLabel: "Optionen anzeigen. {0}  {1} .",
    ListLayoutCompact: "Kompaktansicht",
    ListLayoutCompactDescription: "Anzeigen von Elementen und Details in einer Kompaktliste",
    ListLayoutList: "Listenansicht",
    ListLayoutListDescription: "Anzeigen von Elementen und Details in einer Liste",
    ListLayoutTile: "Kachelansicht",
    ListLayoutTileDescription: "Anzeigen von Elementen mit Kachelvorschauen",
    ListOptionsAlt: "Optionen anzeigen. {0}  ausgewählt.",
    ListOptionsTitle: "Öffnen des Menüs „Ansichtsoptionen“",
    Selected: "Ausgewählt",
    CategoryTranslationNotAvailable: "Eine Übersetzung der ausgewählten Unterkategorie ist für diese Sprache nicht verfügbar.",
    Abandoned: "Verworfen",
    AbandonedPlaylist: "Wiedergabelisten",
    RemoveLanguageLabel: "Sprache entfernen",
    PropertyPaneNone: "keine",
    WebPartModeFull: "Vollständig",
    WebPartModeContentOnly: "Nur Inhalte",
    PropertyPaneFilterCategory: "Kategorie",
    PropertyPaneFilterSubCategory: "Unterkategorie",
    PropertyPaneFilterPlaylist: "Wiedergabeliste",
    AdminSavingNotification: "Wird gespeichert...",
    DataUpgradeReview: "Überprüfung",
    DataUpgradeMultilingual: "Mehrsprachige Unterstützung für Lernpfade ist aktiviert. Überprüfen Sie die für Ihre Website aktivierten Sprachen und schalten Sie die Sprachen aus, die Sie nicht unterstützen möchten.",
    M365Title: "Microsoft 365-Lernpfade",
    ValidateBase: "The base url for the CDN must end in a (/).",
    CustomizeSort: "Customize Sort",
    ResetSort: "Reset Sort"
  };
});