declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Web Part Title (Content Only Mode)",
    LPViewerPropertyDescription: "Custom Learning Properties",
    LPViewerPropertyGroupName: "Default View",
    WebpartModeLabel: "Select Web Part Mode",
    WebpartModeDescription: "How you would like to display the web part",
    ShowNavigationLabel: "Show Custom Learning Navigation Header",
    DefaultFilterLabel: "Select a filter",
    DefaultFilterDescription: "Select a filter to limit the results. You can only filter by one type at a time.",
    DefaultCategoryLabel: "Filter to Category",
    DefaultCategoryDescription: "Select a category to limit results.",
    DefaultSubCategoryLabel: "Filter to Sub-Category",
    DefaultSubCategoryDescription: "Select a sub-category to limit results.",
    DefaultPlaylistLabel: "Filter to Playlist",
    DefaultPlaylistDescription: "Select a category to limit results.",
    DefaultAssetLabel: "Select an Asset",
    DefaultAssetDescription: "Select an asset to display from the playlist.",
    FilterPanelHeader: "Choose the courses that suit you best",
    FilterPanelAudienceLabel: "I am a",
    FilterPanelSkillsetLabel: "My skill set is",
    NavigationHome: "Home",
    SearchResultItemPlayListLabel: "Playlist: ",
    SearchResultItemCategoryLabel: "Category: ",
    SearchPanelPlaceHolderLabel: "Search for Playlists or Assets",
    LinkPanelCopyLabel: "Copy",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Current Playlist: ",
    HeaderPlaylistPanelAdminHeader: "Administration",
    PlaylistOverviewDesignMessage: "During use this area will show other assets in the playlist it's being shown in.",
    PlaylistOverviewHeading: "All steps in playlist",
    BurgerButton: "Burger",
    LinkButton: "Link",
    SearchButton: "Search",
    AdministerPlaylist: "Playlist Administration",
    NoSearchResults: "No search results matched your query.",
    DefaultCDNLabel: "Select Learning Source",
    DefaultCDNDescription: "Select alternate source for learning content.",
    DescriptionFieldLabel: "Description Field",
    ImageSelectorLabel: "Choose an image",
    ImageSelectorButton: "Choose Image",
    DetailEditTitle: "Title",
    DetailEditDescription: "Description",
    DetailEditUrl: "Url",
    DetailEditCategory: "Category",
    DetailEditCategoryNoData: "No Categories are available",
    DetailEditTechnology: "Technology",
    DetailEditLevel: "Level",
    DetailEditAudience: "Audience",
    AssetSearchPlaceHolderLabel: "Search for Existing Assets",
    CategoryHeading: "Add new Subcategory",
    CategoryHeadingLabel: "Subcategory",
    CategoryPlaylistSavedMessage: "Playlist was saved!",
    CategoryPlaylistSaveFailedMessage: "Failed to save playlist!",
    CategoryNewPlayListMessage: "You have made changes to a new playlist. Do you want to discard your changes and continue?",
    CategoryEditedPlayListMessage: "You have made changes to this playlist. Do you want to discard your changes and continue?",
    PlaylistEditAssetSavedMessage: "Asset was saved!",
    PlaylistEditAssetSaveFailedMessage: "Failed to save asset!",
    PlaylistEditCreatePlaylistHeader: "Create a new playlist",
    PlaylistEditPlaylistDetailsHeader: "Playlist Details: ",
    PlaylistEditPlaylistAssetsHeader: "Playlist Assets",
    PlaylistEditEditLabel: "Edit Detail",
    PlaylistEditSaveLabel: "Save Detail",
    PlaylistEditCancelLabel: "Cancel Detail",
    PlaylistEditCloseLabel: "Close Playlist",
    AssetDetailsCreateHeader: "Create a new asset",
    AssetDetailsManageHeader: "Manage Custom Asset:",
    AssetDetailsDetailsHeader: "Asset Details: ",
    AssetDetailsSaveLabel: "Save Asset",
    AssetDetailsCancelLabel: "Cancel Asset",
    AssetDetailsCloseLabel: "Close Asset",
    AssetDetailsOpenPage: "Open Page",
    TechnologyHeadingLabel: "Technology",
    SubcategoryHeadingLabel: "Subcategory Heading",
    PlaylistItemPlaylistHeadingLabel: "Playlist",
    PlaylistItemPlaylistDelete: "Delete Playlist",
    PlaylistEditAssetNewLabel: "New Asset",
    PlaylistRemove: "Remove from Playlist",
    ImageSelectorImageAlt: "Custom Playlist",
    ImageSelectorUrlPlaceholder: "Image Url",
    CategoryHeadingAddPlaylistToSubcategory: "Add new playlist to Subcategory",
    AdminMenuTechnologyLabel: "Technology",
    AdminMenuCategoryLabel: "Category",
    Show: "Show",
    Hide: "Hide",
    Add: "Add",
    Edit: "Edit",
    CloseButton: "Close",
    EditButton: "Edit",
    StepButton: "Step",
    MoveUpButton: "Move Up",
    MoveDownButton: "Move Down",
    SaveButton: "Save",
    CancelButton: "Cancel",
    UpdateButton: "Update",
    DeleteButton: "Delete",
    DetailEditNewPageMessage: "New asset page in Site Pages library.",
    DetailEditExistingPageMessage: "Enter the URL of an existing page.",
    DetailEditNewPageButton: "Create Asset Page",
    DetailEditExistingPageButton: "Enter Url",
    AdminAddCdnLabel: "Add Content Pack",
    AdminEditCdnLabel: "Edit Content Pack",
    AdminDeleteCdnLabel: "Delete Content Pack",
    AdminCdnIdLabel: "Content Pack Id/Partner Id",
    AdminCdnDisplayName: "Display Name",
    AdminCdnBaseUrl: "Base URL",
    AdminCustomCdnTitle: "Custom Content Pack",
    AdminCustomCdnDescription: "Custom Content Packs are an advanced feature and should only be used by Admins with experience administrating web content. Untrustworthy content sources may introduce unsafe content into your site. You should only add sources that you trust. For more information, see Partner Guidance in the learning pathways documentation.",
    AdminConfirmContentPack: "A new browser tab has been started that will allow you to provision the new content pack. When you have successfully done so, click 'Complete' below to update the alternate content list. If you have an error or choose not to install the content pack, please click 'Cancel', you can come back at any time.",
    AdminCdnCompleteButton: "Complete",
    AdminCdnCancelButton: "Cancel",
    AdminCdnSaveButton: "Save",
    AdminCdnUpdateButton: "Update",
    AdminRemoveCdn: "Please confirm you would like to remove the selected CDN?",
    AdminAbout: "About Web Part",
    DocumentationLinkLabel: "Open M365 learning pathways documentation",
    CategoryCopyPlaylistFail: "Failed copying playlist, please contact the administrator or see the browser console for more details.",
    PlaylistEditCopyLabel: "Copy Playlist",
    PlaylistNext: "Next",
    PlaylistPrevious: "Previous",
    PlaylistFullScreen: "Toggle full-screen mode",
    FilterNotSet: "All",
    AdminVersionUpdateNotice: "Your installed Microsoft 365 learning pathways web part is out of date. You are currently running version %0% and the newest version is %1%.",
    AdminVersionUpdateInstructions: "Check out the instructions for 'Updating the solution'.",
    AdminSecurityMessage: "You do not have rights to administrate Microsoft 365 learning pathways. Please talk to administrator about joining the Owners or Members group.",
    AdminConfigIssueMessage: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "Url: Awaiting title...",
    CreatingPage: "Creating page",
    TryAgain: "Try Again",
    AddLanguagePlaceholder: "Add language",
    NotApplicable: "Not Applicable",
    DataUpgradeTitle: "Data Upgrade from",
    DataUpgradeIntro: "You have updated to a major new release of Microsoft 365 learning pathways. To begin the upgrade process press 'Start'",
    DataUpgradeStart: "Start",
    DataUpgradeClose: "Close",
    DataUpgradeIssue: "If you encounter issues performing the update you can request assistance by submitting an  issue to the ",
    DataUpgradeIssueLink: "Microsoft 365 learning pathways GitHub issue list.",
    DataUpgradeLog: "Upgrade Log",
    DataUpgradeComplete: "The upgrade has completed.",
    DataUpgradeErrors: "Errors",
    LogLevel: "Level",
    LogMessage: "Message",
    AboutGroupHeader: "M365 learning pathways",
    AboutGroupTitle: "Current Configuration*",
    AboutGroupTitle2: "(* will be current content pack specific)",
    AboutLearningSiteUrl: "Learning Site Url:",
    AboutBaseCDNPath: "Base CDN Path:",
    AboutTelemetryStatus: "Telemetry Status:",
    AboutCurrentWPVersion: "Current Web Part Version:",
    AboutMultilingualEnabled: "Multilingual Pages Enabled:",
    AboutMultilingualLanguages: "Multilingual Pages Translation Languages:",
    AboutConfiguredLanguages: "Configured Languages:",
    AboutSupportedLanguages: "Content Pack Supported Languages:",
    AboutDefaultSiteLanguage: "Default Site Language:",
    AboutCurrentUserLanguage: "Current User Language:",
    AboutContentPackAssetOrigins: "Content Pack Asset Origins:",
    AboutCurrentCDN: "Current CDN:",
    AboutAllCDNs: "All CDNs:",
    AboutCacheLastUpdate: "Cache Last Update:",
    DocumentLibraries: "Document libraries",
    OpenButtonLabel: "Open",
    CancelButtonLabel: "Cancel",
    UploadFileHeader: "Upload file",
    ChangeFileLinkLabel: "Change file",
    ChooseFileLinkLabel: "Choose file",
    AddFileButtonLabel: "Add file",
    WebSearchLinkLabel: "Web search",
    CreativeCommonsMessage: "These results are tagged with Creative Commons licenses. Review the licenses to ensure you comply.",
    CopyrightWarning: "You are responsible for respecting others' rights, including copyright.",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    LearnMoreLink: "Learn more.",
    NoResultsBadEnglish: "***There is no result found. Try to change the filter options",
    SearchResultAlt: "Image result for {0}.",
    SearchResultAriaLabel: "Press enter to open the image source in a new tab.",
    SearchBoxPlaceholder: "Web search",
    PoweredByBing: "Powered by Bing",
    SizeOptionAll: "All",
    SizeOptionExtraLarge: "Extra Large",
    SizeOptionLarge: "Large",
    SizeOptionMedium: "Medium",
    SizeOptionSmall: "Small",
    LayoutOptionAll: "All",
    LayoutOptionSquare: "Square",
    LayoutOptionTall: "Tall",
    LayoutOptionWide: "Wide",
    LicenseOptionAll: "All",
    LicenseOptionAny: "Creative Commons only",
    RecentDocumentsHeader: "Recent documents",
    Loading: "Loading...",
    NoRecentFiles: "No recent files",
    NoRecentFilesDescription: "Try selecting a file from your site, or upload one from your device.",
    EditedByNamePlate: "edited by ",
    LinkHeader: "From a link",
    LinkFileInstructions: "Paste a link to a file in OneDrive for Business or SharePoint Online",
    NoExternalLinksValidationMessage: "We only support linking to files in your own organization.",
    ProvidedValueIsInvalid: "Provided value is invalid",
    ImageAriaLabelTemplate: ".{0} Image",
    DocumentLabelTemplate: "{0}, Document, Modified {1}, edited by {2}, Private",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, Folder, Modified {1}, edited by {2}, {3} items, Private",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 bytes",
    SizeUnit: [
      "bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "File Picker",
    OrgAssetsTabLabel: "Images and files provided by your organization",
    RecentLinkLabel: "Recent",
    SiteLinkLabel: "Site",
    UploadLinkLabel: "Upload",
    FromLinkLinkLabel: "From a link",
    TypeAriaLabel: "Column operations for File type, Press to sort on File type",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Folder",
    ImageAltText: ".{0} Image",
    NameField: "Name",
    SortedAscending: "Sorted A to Z",
    SortedDescending: "Sorted Z to A",
    ModifiedField: "Date Modified",
    ModifiedByField: "Modified By",
    FileSizeField: "File Size",
    OneDriveEmptyFolderAlt: "Empty folder",
    OneDriveEmptyFolderDescription: "To add files, go to your OneDrive. You can also add files to this folder using the OneDrive app for your computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "This folder is empty",
    ListLayoutAriaLabel: "View options. {0}  {1} .",
    ListLayoutCompact: "Compact view",
    ListLayoutCompactDescription: "View items and details in a compact list",
    ListLayoutList: "List view",
    ListLayoutListDescription: "View items and details in a list",
    ListLayoutTile: "Tile view",
    ListLayoutTileDescription: "View items with tile previews",
    ListOptionsAlt: "View options. {0}  selected .",
    ListOptionsTitle: "Open the view options menu",
    Selected: "selected",
    CategoryTranslationNotAvailable: "A translation of the selected Sub Category is not available for this language.",
    Abandoned: "Abandoned",
    AbandonedPlaylist: "Playlists",
    RemoveLanguageLabel: "Remove Language",
    PropertyPaneNone: "none",
    WebPartModeFull: "Full",
    WebPartModeContentOnly: "Content Only",
    PropertyPaneFilterCategory: "Category",
    PropertyPaneFilterSubCategory: "Sub-Category",
    PropertyPaneFilterPlaylist: "Playlist",
    AdminSavingNotification: "Saving..",
    DataUpgradeReview: "Review",
    DataUpgradeMultilingual: "Multilingual support is enabled for learning pathways. Review the languages enabled for your site and turn off the languages you don’t want to support.",
    M365Title: "Microsoft 365 learning pathways",
    ValidateBase: "The base url for the CDN must end in a (/).",
    CustomizeSort: "Customize Sort",
    ResetSort: "Reset Sort"
  };
});