declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Título del elemento web (modo de solo contenido)",
    LPViewerPropertyDescription: "Propiedades del aprendizaje personalizado",
    LPViewerPropertyGroupName: "Vista predeterminada",
    WebpartModeLabel: "Seleccionar el modo del elemento web",
    WebpartModeDescription: "Cómo desea mostrar el elemento web",
    ShowNavigationLabel: "Mostrar encabezado de navegación de aprendizaje personalizado",
    DefaultFilterLabel: "Seleccionar un filtro",
    DefaultFilterDescription: "Seleccionar un filtro para limitar los resultados. Solo puede filtrar por un tipo cada vez.",
    DefaultCategoryLabel: "Filtrar según la categoría",
    DefaultCategoryDescription: "Seleccione una categoría para limitar los resultados.",
    DefaultSubCategoryLabel: "Filtrar según la subcategoría",
    DefaultSubCategoryDescription: "Seleccione una subcategoría para limitar los resultados.",
    DefaultPlaylistLabel: "Filtrar según la lista de reproducción",
    DefaultPlaylistDescription: "Seleccione una categoría para limitar los resultados.",
    DefaultAssetLabel: "Seleccionar un activo",
    DefaultAssetDescription: "Seleccione el activo de la lista de reproducción que se mostrará.",
    FilterPanelHeader: "Elija los cursos que más le convengan",
    FilterPanelAudienceLabel: "Soy",
    FilterPanelSkillsetLabel: "Mi conjunto de aptitudes es",
    NavigationHome: "Inicio",
    SearchResultItemPlayListLabel: "Lista de reproducción: ",
    SearchResultItemCategoryLabel: "Categoría: ",
    SearchPanelPlaceHolderLabel: "Buscar listas de reproducción o activos",
    LinkPanelCopyLabel: "Copiar",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Lista de reproducción actual: ",
    HeaderPlaylistPanelAdminHeader: "Administración",
    PlaylistOverviewDesignMessage: "Durante el uso, en esta área se mostrarán otros activos en la lista de reproducción en la que se muestra.",
    PlaylistOverviewHeading: "Todos los pasos de la lista de reproducción",
    BurgerButton: "Hamburguesa",
    LinkButton: "Vínculo",
    SearchButton: "Búsqueda",
    AdministerPlaylist: "Administración de lista de reproducción",
    NoSearchResults: "Los resultados de la búsqueda no coinciden con la consulta.",
    DefaultCDNLabel: "Seleccionar origen de aprendizaje",
    DefaultCDNDescription: "Seleccione un origen alternativo para el contenido de aprendizaje.",
    DescriptionFieldLabel: "Campo de descripción",
    ImageSelectorLabel: "Seleccionar una imagen",
    ImageSelectorButton: "Seleccionar imagen",
    DetailEditTitle: "Título",
    DetailEditDescription: "Descripción",
    DetailEditUrl: "URL",
    DetailEditCategory: "Categoría",
    DetailEditCategoryNoData: "No hay categorías disponibles",
    DetailEditTechnology: "Tecnología",
    DetailEditLevel: "Nivel",
    DetailEditAudience: "Audiencia",
    AssetSearchPlaceHolderLabel: "Buscar activos existentes",
    CategoryHeading: "Agregar nueva subcategoría",
    CategoryHeadingLabel: "Subcategoría",
    CategoryPlaylistSavedMessage: "La lista de reproducción se ha guardado.",
    CategoryPlaylistSaveFailedMessage: "No se pudo guardar la lista de reproducción.",
    CategoryNewPlayListMessage: "Ha realizado cambios en una nueva lista de reproducción. ¿Desea descartar los cambios y continuar?",
    CategoryEditedPlayListMessage: "Ha realizado cambios en esta lista de reproducción. ¿Desea descartar los cambios y continuar?",
    PlaylistEditAssetSavedMessage: "Se ha guardado el activo.",
    PlaylistEditAssetSaveFailedMessage: "No se pudo guardar el activo.",
    PlaylistEditCreatePlaylistHeader: "Crear una nueva lista de reproducción",
    PlaylistEditPlaylistDetailsHeader: "Detalles de la lista de reproducción: ",
    PlaylistEditPlaylistAssetsHeader: "Activos de la lista de reproducción",
    PlaylistEditEditLabel: "Editar detalle",
    PlaylistEditSaveLabel: "Guardar detalle",
    PlaylistEditCancelLabel: "Cancelar detalle",
    PlaylistEditCloseLabel: "Cerrar lista de reproducción",
    AssetDetailsCreateHeader: "Crear un nuevo activo",
    AssetDetailsManageHeader: "Administrar activo personalizado:",
    AssetDetailsDetailsHeader: "Detalles de activos: ",
    AssetDetailsSaveLabel: "Guardar activo",
    AssetDetailsCancelLabel: "Cancelar activo",
    AssetDetailsCloseLabel: "Cerrar activo",
    AssetDetailsOpenPage: "Abrir página",
    TechnologyHeadingLabel: "Tecnología",
    SubcategoryHeadingLabel: "Encabezado de subcategoría",
    PlaylistItemPlaylistHeadingLabel: "Lista de reproducción",
    PlaylistItemPlaylistDelete: "Eliminar lista de reproducción",
    PlaylistEditAssetNewLabel: "Nuevo activo",
    PlaylistRemove: "Quitar de la lista de reproducción",
    ImageSelectorImageAlt: "Lista de reproducción personalizada",
    ImageSelectorUrlPlaceholder: "Dirección URL de la imagen",
    CategoryHeadingAddPlaylistToSubcategory: "Agregar nueva lista de reproducción a la subcategoría",
    AdminMenuTechnologyLabel: "Tecnología",
    AdminMenuCategoryLabel: "Categoría",
    Show: "Mostrar",
    Hide: "Ocultar",
    Add: "Agregar",
    Edit: "Editar",
    CloseButton: "Cerrar",
    EditButton: "Editar",
    StepButton: "Paso",
    MoveUpButton: "Subir",
    MoveDownButton: "Bajar",
    SaveButton: "Guardar",
    CancelButton: "Cancelar",
    UpdateButton: "Actualizar",
    DeleteButton: "Eliminar",
    DetailEditNewPageMessage: "Página del nuevo activo de la biblioteca de Páginas del sitio.",
    DetailEditExistingPageMessage: "Escriba la dirección URL de una página existente.",
    DetailEditNewPageButton: "Página Crear activo",
    DetailEditExistingPageButton: "Escriba la dirección URL",
    AdminAddCdnLabel: "Agregar paquete de contenido",
    AdminEditCdnLabel: "Editar paquete de contenido",
    AdminDeleteCdnLabel: "Eliminar paquete de contenido",
    AdminCdnIdLabel: "Id. de paquete de contenido/Id. de partner",
    AdminCdnDisplayName: "Nombre para mostrar",
    AdminCdnBaseUrl: "URL base",
    AdminCustomCdnTitle: "Paquete de contenido personalizado",
    AdminCustomCdnDescription: "Los paquetes de contenido personalizados son una característica avanzada y solo deben usarlos los administradores con experiencia en la administración de contenido web. Los orígenes de contenido poco confiables pueden introducir contenido no seguro en el sitio. Solo debe agregar orígenes de confianza. Para obtener más información, vea las instrucciones del partner en la documentación de las formas de aprendizaje.",
    AdminConfirmContentPack: "Se ha iniciado una nueva pestaña del explorador que le permitirá aprovisionar el nuevo paquete de contenido. Cuando lo haya realizado correctamente, haga clic en \"Completar\" a continuación para actualizar la lista de contenido alternativo. Si se produce un error o decide no instalar el paquete de contenido, haga clic en \"Cancelar\". Puede volver a él en cualquier momento.",
    AdminCdnCompleteButton: "Completar",
    AdminCdnCancelButton: "Cancelar",
    AdminCdnSaveButton: "Guardar",
    AdminCdnUpdateButton: "Actualizar",
    AdminRemoveCdn: "Confirme que le gustaría quitar la red CDN seleccionada.",
    AdminAbout: "Acerca del elemento web",
    DocumentationLinkLabel: "Abra la documentación acerca de formas de aprendizaje de M365",
    CategoryCopyPlaylistFail: "No se pudo copiar la lista de reproducción. Póngase en contacto con el administrador o consulte la consola del explorador para obtener más información.",
    PlaylistEditCopyLabel: "Copiar lista de reproducción",
    PlaylistNext: "Siguiente",
    PlaylistPrevious: "Anterior",
    PlaylistFullScreen: "Activar o desactivar el modo de pantalla completa",
    FilterNotSet: "Todo",
    AdminVersionUpdateNotice: "El elemento web instalado de las formas de aprendizaje de Microsoft 365 está obsoleto. Se está ejecutando la versión %0% y la versión más reciente es %1%.",
    AdminVersionUpdateInstructions: "Consulte las instrucciones para \"Actualizar la solución\".",
    AdminSecurityMessage: "No tiene permisos para administrar las formas de aprendizaje de Microsoft 365. Póngase en contacto con el administrador para unirse al grupo de propietarios o miembros.",
    AdminConfigIssueMessage: "Las formas de aprendizaje de Microsoft 365 tienen un problema de configuración. Póngase en contacto con el administrador para obtener ayuda. [Administradores: consulten la consola del explorador para obtener registros detallados. Para obtener asistencia técnica, consulten la lista de problemas en https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "URL: Esperando por el título...",
    CreatingPage: "Creando página",
    TryAgain: "Volver a intentar",
    AddLanguagePlaceholder: "Añadir lenguaje",
    NotApplicable: "No aplicable",
    DataUpgradeTitle: "Actualización de datos de",
    DataUpgradeIntro: "Se ha actualizado a una nueva versión importante de las formas de aprendizaje de Microsoft 365. Para iniciar el proceso de actualización, pulse \"Inicio\".",
    DataUpgradeStart: "Inicio",
    DataUpgradeClose: "Cerrar",
    DataUpgradeIssue: "Si tiene algún problema al realizar la actualización, puede solicitar asistencia enviando un problema a la ",
    DataUpgradeIssueLink: "Lista de problemas de GitHub de las formas de aprendizaje de Microsoft 365.",
    DataUpgradeLog: "Registro de actualizaciones",
    DataUpgradeComplete: "La actualización se ha completado.",
    DataUpgradeErrors: "Errores",
    LogLevel: "Nivel",
    LogMessage: "Mensaje",
    AboutGroupHeader: "Formas de aprendizaje de M365",
    AboutGroupTitle: "Configuración actual*",
    AboutGroupTitle2: "(* será específica para el paquete de contenido actual)",
    AboutLearningSiteUrl: "Dirección URL del sitio de aprendizaje:",
    AboutBaseCDNPath: "Ruta de acceso CDN base:",
    AboutTelemetryStatus: "Estado de telemetría:",
    AboutCurrentWPVersion: "Versión actual del elemento web:",
    AboutMultilingualEnabled: "Páginas multilingües habilitadas:",
    AboutMultilingualLanguages: "Idiomas de traducción de páginas multilingües:",
    AboutConfiguredLanguages: "Idiomas configurados:",
    AboutSupportedLanguages: "Idiomas compatibles con el paquete de contenido:",
    AboutDefaultSiteLanguage: "Idioma predeterminado del sitio:",
    AboutCurrentUserLanguage: "Idioma actual del usuario:",
    AboutContentPackAssetOrigins: "Orígenes de los activos del paquete de contenido:",
    AboutCurrentCDN: "CDN actual:",
    AboutAllCDNs: "Todos los CDN:",
    AboutCacheLastUpdate: "Última actualización de la caché:",
    DocumentLibraries: "Bibliotecas de documentos",
    OpenButtonLabel: "Abrir",
    CancelButtonLabel: "Cancelar",
    UploadFileHeader: "Cargar archivo",
    ChangeFileLinkLabel: "Cambiar archivo",
    ChooseFileLinkLabel: "Seleccionar archivo",
    AddFileButtonLabel: "Agregar archivo",
    WebSearchLinkLabel: "Búsqueda web",
    CreativeCommonsMessage: "Estos resultados se etiquetan con licencias de Creative Commons. Revise las licencias para asegurarse de que las cumple.",
    CopyrightWarning: "Es su responsabilidad respetar los derechos de los demás, incluidos los derechos de autor.",
    CopyrightUrl: "https://www.microsoft.com/es-es/legal/copyright/default.aspx",
    LearnMoreLink: "Obtenga más información.",
    NoResultsBadEnglish: "***No se encontraron resultados. Pruebe a cambiar las opciones del filtro",
    SearchResultAlt: "Resultado de la imagen para {0}.",
    SearchResultAriaLabel: "Pulse Entrar para abrir el origen de la imagen en una nueva pestaña.",
    SearchBoxPlaceholder: "Búsqueda web",
    PoweredByBing: "Con tecnología de Bing",
    SizeOptionAll: "Todo",
    SizeOptionExtraLarge: "Extra grande",
    SizeOptionLarge: "Grande",
    SizeOptionMedium: "Mediano",
    SizeOptionSmall: "Pequeño",
    LayoutOptionAll: "Todo",
    LayoutOptionSquare: "Cuadrado",
    LayoutOptionTall: "Alto",
    LayoutOptionWide: "Ancho",
    LicenseOptionAll: "Todo",
    LicenseOptionAny: "Solo Creative Commons",
    RecentDocumentsHeader: "Documentos recientes",
    Loading: "Cargando…",
    NoRecentFiles: "No hay archivos recientes",
    NoRecentFilesDescription: "Pruebe a seleccionar un archivo del sitio, o bien cargar uno desde el dispositivo.",
    EditedByNamePlate: "editado por ",
    LinkHeader: "Desde un vínculo",
    LinkFileInstructions: "Pegar un vínculo a un archivo en OneDrive para la Empresa o SharePoint Online",
    NoExternalLinksValidationMessage: "Solo se admiten los vínculos a los archivos de su organización.",
    ProvidedValueIsInvalid: "El valor proporcionado no es válido",
    ImageAriaLabelTemplate: "Imagen .{0}",
    DocumentLabelTemplate: "{0}, documento, modificado \\ {1 \\}, modificado por \\ {2 \\}, privado",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, carpeta, modificado \\ {1 \\}, editado por \\ {2 \\}, {3} elementos, privado",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 bytes",
    SizeUnit: [
      "bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Selector de archivos",
    OrgAssetsTabLabel: "Archivos e imágenes proporcionados por la organización",
    RecentLinkLabel: "Reciente",
    SiteLinkLabel: "Sitio",
    UploadLinkLabel: "Cargar",
    FromLinkLinkLabel: "Desde un vínculo",
    TypeAriaLabel: "Operaciones de columna para Tipo de archivo, Pulse para ordenar por Tipo de archivo",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Folder",
    ImageAltText: "Imagen .{0}",
    NameField: "Nombre",
    SortedAscending: "Ordenado de la A a la Z",
    SortedDescending: "Ordenado de la Z a la A",
    ModifiedField: "Fecha de modificación",
    ModifiedByField: "Modificado por",
    FileSizeField: "Tamaño de archivo",
    OneDriveEmptyFolderAlt: "Carpeta vacía",
    OneDriveEmptyFolderDescription: "Para agregar archivos, vaya a OneDrive. También puede agregar archivos a esta carpeta con la aplicación de OneDrive de su equipo.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Esta carpeta está vacía",
    ListLayoutAriaLabel: "Ver opciones. {0}  {1} .",
    ListLayoutCompact: "Vista compacta",
    ListLayoutCompactDescription: "Ver elementos y detalles en una lista compacta",
    ListLayoutList: "Vista de lista",
    ListLayoutListDescription: "Ver elementos y detalles en una lista",
    ListLayoutTile: "Vista de mosaico",
    ListLayoutTileDescription: "Ver elementos con vistas previas en mosaico",
    ListOptionsAlt: "Opciones de vista. {0}  seleccionadas .",
    ListOptionsTitle: "Abrir el menú de opciones de vista",
    Selected: "seleccionadas",
    CategoryTranslationNotAvailable: "La traducción de la subcategoría seleccionada no está disponible para este idioma.",
    Abandoned: "Abandonada",
    AbandonedPlaylist: "Listas de reproducción",
    RemoveLanguageLabel: "Quitar idioma",
    PropertyPaneNone: "ninguno",
    WebPartModeFull: "Completo",
    WebPartModeContentOnly: "Solo contenido",
    PropertyPaneFilterCategory: "Categoría",
    PropertyPaneFilterSubCategory: "Subcategoría",
    PropertyPaneFilterPlaylist: "Lista de reproducción",
    AdminSavingNotification: "Guardando..",
    DataUpgradeReview: "Revisar",
    DataUpgradeMultilingual: "El soporte técnico multilingüe está habilitado para las formas de aprendizaje. Revise los idiomas habilitados para su sitio y desactive los idiomas a los que no desea dar soporte técnico.",
    M365Title: "Formas de aprendizaje de Microsoft 365",
    ValidateBase: "The base url for the CDN must end in a (/).",
    CustomizeSort: "Customize Sort",
    ResetSort: "Reset Sort"
  };
});