declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Titre du composant WebPart (mode contenu uniquement)",
    LPViewerPropertyDescription: "Propriétés d’apprentissage personnalisée",
    LPViewerPropertyGroupName: "Affichage par défaut",
    WebpartModeLabel: "Sélectionner le mode du composant WebPart",
    WebpartModeDescription: "Mode d’affichage du composant WebPart",
    ShowNavigationLabel: "Afficher l’en-tête de navigation de formation personnalisée",
    DefaultFilterLabel: "Sélectionner un filtre",
    DefaultFilterDescription: "Sélectionner un filtre pour limiter la réponse. Vous pouvez uniquement filtrer un seul texte à la fois.",
    DefaultCategoryLabel: "Filtrer par catégorie",
    DefaultCategoryDescription: "Sélectionner une catégorie pour limiter les résultats.",
    DefaultSubCategoryLabel: "Filtrer par sous-catégorie",
    DefaultSubCategoryDescription: "Sélectionner une sous-catégorie pour limiter les résultats.",
    DefaultPlaylistLabel: "Filtrer par playlist",
    DefaultPlaylistDescription: "Sélectionner une catégorie pour limiter les résultats.",
    DefaultAssetLabel: "Sélectionner un bien",
    DefaultAssetDescription: "Sélectionner un bien à afficher dans la liste de diffusion.",
    FilterPanelHeader: "Sélectionner les cours qui vous conviennent le mieux",
    FilterPanelAudienceLabel: "Je suis un(e)",
    FilterPanelSkillsetLabel: "Mes compétences sont les suivantes",
    NavigationHome: "Accueil",
    SearchResultItemPlayListLabel: "Playlist : ",
    SearchResultItemCategoryLabel: "Catégorie : ",
    SearchPanelPlaceHolderLabel: "Rechercher des playlists ou des biens",
    LinkPanelCopyLabel: "Copier",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Playlist actuelle : ",
    HeaderPlaylistPanelAdminHeader: "Administration",
    PlaylistOverviewDesignMessage: "Pendant l’utilisation, cette zone affiche les autres éléments dans la playlist dans laquelle elle apparaît.",
    PlaylistOverviewHeading: "Toutes les étapes de la playlist",
    BurgerButton: "Burger",
    LinkButton: "Liens",
    SearchButton: "Recherche",
    AdministerPlaylist: "Administration des playlists",
    NoSearchResults: "Aucun résultat de recherche ne correspond à votre requête.",
    DefaultCDNLabel: "Sélectionner une source d’apprentissage",
    DefaultCDNDescription: "Sélectionner autre source pour le contenu d’apprentissage.",
    DescriptionFieldLabel: "Champ de description",
    ImageSelectorLabel: "Choisir une image",
    ImageSelectorButton: "Choisir une image",
    DetailEditTitle: "Titre",
    DetailEditDescription: "Description",
    DetailEditUrl: "Url",
    DetailEditCategory: "Catégorie",
    DetailEditCategoryNoData: "Aucune catégorie n’est disponible",
    DetailEditTechnology: "Technologie",
    DetailEditLevel: "Niveau",
    DetailEditAudience: "Audience",
    AssetSearchPlaceHolderLabel: "Rechercher des biens existants",
    CategoryHeading: "Ajouter une nouvelle sous-catégorie",
    CategoryHeadingLabel: "Sous-catégorie",
    CategoryPlaylistSavedMessage: "La playlist a été enregistrée !",
    CategoryPlaylistSaveFailedMessage: "L’enregistrement de la playlist a échoué !",
    CategoryNewPlayListMessage: "Vous avez apporté des modifications à une nouvelle playlist. Voulez-vous ignorer vos modifications et continuer ?",
    CategoryEditedPlayListMessage: "Vous avez apporté des modifications à cette playlist. Voulez-vous ignorer vos modifications et continuer ?",
    PlaylistEditAssetSavedMessage: "L’actif a été enregistré !",
    PlaylistEditAssetSaveFailedMessage: "L’enregistrement du bien a échoué !",
    PlaylistEditCreatePlaylistHeader: "Créer une nouvelle playlist",
    PlaylistEditPlaylistDetailsHeader: "Détails de la playlist : ",
    PlaylistEditPlaylistAssetsHeader: "Bien de sélection",
    PlaylistEditEditLabel: "Modifier des détails",
    PlaylistEditSaveLabel: "Enregistrer des détails",
    PlaylistEditCancelLabel: "Annuler des détails",
    PlaylistEditCloseLabel: "Fermer une playlist",
    AssetDetailsCreateHeader: "Créer une nouvelle diapositive",
    AssetDetailsManageHeader: "Gérer le bien personnalisé :",
    AssetDetailsDetailsHeader: "Détails du bien : ",
    AssetDetailsSaveLabel: "Enregistrer un bien",
    AssetDetailsCancelLabel: "Annuler un bien",
    AssetDetailsCloseLabel: "Fermer un bien",
    AssetDetailsOpenPage: "Ouvrir une page",
    TechnologyHeadingLabel: "Technologie",
    SubcategoryHeadingLabel: "Titre de la sous-catégorie",
    PlaylistItemPlaylistHeadingLabel: "Playlist",
    PlaylistItemPlaylistDelete: "Fermer une playlist",
    PlaylistEditAssetNewLabel: "Nouveau bien",
    PlaylistRemove: "Supprimer de la playlist",
    ImageSelectorImageAlt: "Playlist personnalisée",
    ImageSelectorUrlPlaceholder: "URL image",
    CategoryHeadingAddPlaylistToSubcategory: "Ajouter une nouvelle playlist à une sous-catégorie",
    AdminMenuTechnologyLabel: "Technologie",
    AdminMenuCategoryLabel: "Catégorie",
    Show: "Afficher",
    Hide: "Masquer",
    Add: "Ajouter",
    Edit: "Modifier",
    CloseButton: "Fermer",
    EditButton: "Modifier",
    StepButton: "Étape",
    MoveUpButton: "Déplacer vers le haut",
    MoveDownButton: "Déplacer vers le bas",
    SaveButton: "Enregistrer",
    CancelButton: "Annuler",
    UpdateButton: "Update",
    DeleteButton: "Supprimer",
    DetailEditNewPageMessage: "Page nouveau bien dans la bibliothèque pages du site.",
    DetailEditExistingPageMessage: "Entrez l’URL d’une page existante.",
    DetailEditNewPageButton: "Page créer un bien",
    DetailEditExistingPageButton: "Entrez l’URL",
    AdminAddCdnLabel: "Ajouter un pack de contenu",
    AdminEditCdnLabel: "Modifier un pack de contenu",
    AdminDeleteCdnLabel: "Supprimer le Pack de contenu",
    AdminCdnIdLabel: "ID du Pack de contenu/ID de partenaire",
    AdminCdnDisplayName: "Nom d’affichage",
    AdminCdnBaseUrl: "URL de base",
    AdminCustomCdnTitle: "Pack de contenu personnalisé",
    AdminCustomCdnDescription: "Les packs de contenu personnalisés constituent une fonctionnalité avancée et ne doivent être utilisés que par les administrateurs ayant une expérience d’administration du contenu web. Les sources de contenu non fiables peuvent introduire du contenu dangereux sur votre site. Vous devez uniquement ajouter des sources dignes de confiance. Pour plus d’informations, voir conseils pour les partenaires dans la documentation sur les voies d’apprentissage.",
    AdminConfirmContentPack: "Un nouvel onglet de navigateur, qui vous permet de mettre en service le nouveau Pack de contenu, a été créé. Lorsque vous avez terminé, cliquez sur « Terminé » ci-dessous pour mettre à jour la liste de contenu de remplacement. Si vous rencontrez une erreur ou si vous choisissez de ne pas installer le Pack de contenu, cliquez sur Annuler, vous pouvez revenir à tout moment.",
    AdminCdnCompleteButton: "Exécuter",
    AdminCdnCancelButton: "Annuler",
    AdminCdnSaveButton: "Enregistrer",
    AdminCdnUpdateButton: "Update",
    AdminRemoveCdn: "Veuillez confirmer que vous souhaitez supprimer le réseau de distribution de contenu sélectionné ?",
    AdminAbout: "À propos du composant WebPart",
    DocumentationLinkLabel: "Ouvrir la documentation sur les parcours d’apprentissage M365",
    CategoryCopyPlaylistFail: "La copie de sélection a échoué. pour plus d’informations, contactez l’administrateur ou consultez la console de navigateur.",
    PlaylistEditCopyLabel: "Copier la playlist",
    PlaylistNext: "Suivant",
    PlaylistPrevious: "Précédent",
    PlaylistFullScreen: "Activer/désactiver le mode plein écran",
    FilterNotSet: "Tous",
    AdminVersionUpdateNotice: "Le composant WebPart parcours d’apprentissage Microsoft 365 est obsolète. Vous exécutez actuellement la version %0% et la version la plus récente est %1%.",
    AdminVersionUpdateInstructions: "Consultez la procédure de mise à jour de la solution.",
    AdminSecurityMessage: "Vous n’êtes pas autorisé à gérer les parcours d’apprentissage de Microsoft 365. Contactez l’administrateur pour rejoindre le groupe propriétaires ou membres.",
    AdminConfigIssueMessage: "Les parcours d'apprentissage de Microsoft 365 rencontrer un problème de configuration. Demandez de l’aide à votre administrateur. [Administrateur : Pour plus d’informations, voir la console du navigateur. Pour obtenir une assistance technique, consultez la liste des problèmes sur https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "Url : Titre en attente...",
    CreatingPage: "Création de la page",
    TryAgain: "Réessayez.",
    AddLanguagePlaceholder: "Ajouter une langue",
    NotApplicable: "Non applicable",
    DataUpgradeTitle: "Mise à niveau à partir de",
    DataUpgradeIntro: "Vous avez mis à jour vers une nouvelle version de Microsoft 365 parcours d’apprentissage inédites. Pour démarrer le processus de mise à niveau, appuyez sur« Démarrer »",
    DataUpgradeStart: "Début",
    DataUpgradeClose: "Fermer",
    DataUpgradeIssue: "Si vous rencontrez des problèmes lors de l’exécution de la mise à jour, vous pouvez demander de l’aide en envoyant un problème au ",
    DataUpgradeIssueLink: "Liste des problèmes GitHub liés aux parcours d’apprentissage Microsoft 365.",
    DataUpgradeLog: "Journal de mise à niveau",
    DataUpgradeComplete: "La mise à niveau est terminée.",
    DataUpgradeErrors: "Erreurs",
    LogLevel: "Niveau",
    LogMessage: "Message",
    AboutGroupHeader: "Parcours d’apprentissage M365",
    AboutGroupTitle: "Configuration actuelle*",
    AboutGroupTitle2: "(* est propre au Pack de contenu actuel)",
    AboutLearningSiteUrl: "URL du site d’apprentissage :",
    AboutBaseCDNPath: "Chemin d’accès au CDN de base :",
    AboutTelemetryStatus: "État de la télémétrie :",
    AboutCurrentWPVersion: "Version actuelle du composant WebPart :",
    AboutMultilingualEnabled: "Pages multilingues activées :",
    AboutMultilingualLanguages: "Langues de traduction des pages multilingues :",
    AboutConfiguredLanguages: "Langues configurées :",
    AboutSupportedLanguages: "Langues prises en charge du Packs de contenu :",
    AboutDefaultSiteLanguage: "Langue du site par défaut :",
    AboutCurrentUserLanguage: "Langue de l’utilisateur actuel :",
    AboutContentPackAssetOrigins: "Origines des ressources du Packs contenu :",
    AboutCurrentCDN: "CDN actuel :",
    AboutAllCDNs: "Tous les CDN :",
    AboutCacheLastUpdate: "Dernière mise à jour du cache :",
    DocumentLibraries: "Bibliothèques de documents",
    OpenButtonLabel: "Ouvrir",
    CancelButtonLabel: "Annuler",
    UploadFileHeader: "Télécharger un fichier",
    ChangeFileLinkLabel: "Modifier un fichier",
    ChooseFileLinkLabel: "Choisir un fichier",
    AddFileButtonLabel: "Ajouter un fichier",
    WebSearchLinkLabel: "Recherche sur le web",
    CreativeCommonsMessage: "Ces résultats sont balisés avec des licences Creative Commons. Examinez les licences pour vous assurer qu'elles sont conformes.",
    CopyrightWarning: "Vous êtes tenu de respecter les droits d’autrui, notamment les droits d’auteur.",
    CopyrightUrl: "https://www.microsoft.com/fr-FR/legal/copyright/default.aspx",
    LearnMoreLink: "En savoir plus.",
    NoResultsBadEnglish: "***Aucun résultat trouvé. Essayez de modifier les options de filtre",
    SearchResultAlt: "Résultat de l’image pour {0}.",
    SearchResultAriaLabel: "Appuyez sur entrée pour ouvrir la source de l’image dans un nouvel onglet.",
    SearchBoxPlaceholder: "Recherche sur le web",
    PoweredByBing: "Optimisé par Bing",
    SizeOptionAll: "Tous",
    SizeOptionExtraLarge: "Très grande",
    SizeOptionLarge: "Grande",
    SizeOptionMedium: "Moyenne",
    SizeOptionSmall: "Petite",
    LayoutOptionAll: "Tous",
    LayoutOptionSquare: "Carré",
    LayoutOptionTall: "Grand",
    LayoutOptionWide: "Larges",
    LicenseOptionAll: "Tous",
    LicenseOptionAny: "Creative Commons uniquement",
    RecentDocumentsHeader: "Documents récents",
    Loading: "Chargement...",
    NoRecentFiles: "Aucun fichier récent",
    NoRecentFilesDescription: "Essayez de sélectionner un fichier à partir de votre site, ou téléchargez-en un à partir de votre appareil.",
    EditedByNamePlate: "modifié par ",
    LinkHeader: "À partir d’un lien",
    LinkFileInstructions: "Coller un lien vers un fichier dans OneDrive Entreprise ou SharePoint Online",
    NoExternalLinksValidationMessage: "Nous ne prenons en charge que la liaison avec des fichiers de votre organisation.",
    ProvidedValueIsInvalid: "Valeur fournie non valide",
    ImageAriaLabelTemplate: ".{0} Image",
    DocumentLabelTemplate: "{0}, Document, Modifié {1}, modifié par {2}, Privé",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, Dossier, Modifié {1}, modifié par {2}, {3} éléments, Privé",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 octet",
    SizeUnit: [
      "octets",
      "Ko",
      "Mo",
      "Go",
      "To",
      "PB",
      "EV",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Sélecteur de fichiers",
    OrgAssetsTabLabel: "Images et fichiers fournis par votre organisation",
    RecentLinkLabel: "Récent",
    SiteLinkLabel: "Site",
    UploadLinkLabel: "Charger",
    FromLinkLinkLabel: "À partir d’un lien",
    TypeAriaLabel: "Opérations de colonne pour le type de fichier, appuyer pour trier sur le type de fichier",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Dossier",
    ImageAltText: ".{0} Image",
    NameField: "Nom",
    SortedAscending: "Trié de A à Z",
    SortedDescending: "Trier de Z à A",
    ModifiedField: "Date de modification",
    ModifiedByField: "Modifié par",
    FileSizeField: "Taille de fichier",
    OneDriveEmptyFolderAlt: "Dossier vide",
    OneDriveEmptyFolderDescription: "Pour ajouter des fichiers, accédez à votre espace OneDrive. Vous pouvez également ajouter des fichiers à ce dossier à l’aide de l’application OneDrive sur votre ordinateur.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Ce dossier est vide",
    ListLayoutAriaLabel: "Afficher les options. {0}  {1} .",
    ListLayoutCompact: "Affichage compact",
    ListLayoutCompactDescription: "Afficher les éléments et les détails dans une liste compacte",
    ListLayoutList: "Affichage Liste",
    ListLayoutListDescription: "Afficher les éléments et les détails dans une liste",
    ListLayoutTile: "Mode vignette",
    ListLayoutTileDescription: "Afficher les éléments avec des aperçus de vignettes",
    ListOptionsAlt: "Options d’affichage. {0}  sélectionné.",
    ListOptionsTitle: "Ouvrir le menu options d’affichage",
    Selected: "Sélectionné",
    CategoryTranslationNotAvailable: "Une traduction de la sous-catégorie sélectionnée n’est pas disponible pour cette langue.",
    Abandoned: "Abandonné",
    AbandonedPlaylist: "Playlists",
    RemoveLanguageLabel: "Supprimer la langue",
    PropertyPaneNone: "aucune",
    WebPartModeFull: "Complet",
    WebPartModeContentOnly: "Contenu uniquement",
    PropertyPaneFilterCategory: "Catégorie",
    PropertyPaneFilterSubCategory: "Sous-catégorie",
    PropertyPaneFilterPlaylist: "Playlist",
    AdminSavingNotification: "Enregistrement...",
    DataUpgradeReview: "Révision",
    DataUpgradeMultilingual: "La prise en charge multilingue est activée pour les voies d’apprentissage. Vérifiez les langues activées pour votre site et désactivez celles que vous ne voulez pas prendre en charge.",
    M365Title: "Parcours d’apprentissage de Microsoft 365",
    ValidateBase: "The base url for the CDN must end in a (/).",
    CustomizeSort: "Customize Sort",
    ResetSort: "Reset Sort"
  };
});