declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Titolo web part (modalità solo contenuto)",
    LPViewerPropertyDescription: "Proprietà di apprendimento personalizzate",
    LPViewerPropertyGroupName: "Visualizzazione predefinita",
    WebpartModeLabel: "Seleziona modalità web part",
    WebpartModeDescription: "Come si vuole visualizzare la web part",
    ShowNavigationLabel: "Mostra intestazione di spostamento di apprendimento personalizzato",
    DefaultFilterLabel: "Seleziona un filtro",
    DefaultFilterDescription: "Selezionare un filtro per limitare i risultati. È possibile filtrare solo un tipo alla volta.",
    DefaultCategoryLabel: "Filtra per categoria",
    DefaultCategoryDescription: "Selezionare una categoria per limitare i risultati.",
    DefaultSubCategoryLabel: "Filtra per sottocategoria",
    DefaultSubCategoryDescription: "Selezionare una sottocategoria per limitare i risultati.",
    DefaultPlaylistLabel: "Filtra per playlist",
    DefaultPlaylistDescription: "Selezionare una categoria per limitare i risultati.",
    DefaultAssetLabel: "Seleziona una risorsa",
    DefaultAssetDescription: "Selezionare una risorsa da visualizzare nella playlist.",
    FilterPanelHeader: "Scegliere i corsi più adatti alle proprie esigenze",
    FilterPanelAudienceLabel: "Sono",
    FilterPanelSkillsetLabel: "Competenze",
    NavigationHome: "Home",
    SearchResultItemPlayListLabel: "Playlist: ",
    SearchResultItemCategoryLabel: "Categoria: ",
    SearchPanelPlaceHolderLabel: "Cerca playlist o risorse",
    LinkPanelCopyLabel: "Copia",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Playlist corrente: ",
    HeaderPlaylistPanelAdminHeader: "Amministrazione",
    PlaylistOverviewDesignMessage: "Durante l'uso di quest'area verranno visualizzate altre risorse della playlist in cui sono visualizzate.",
    PlaylistOverviewHeading: "Tutti i passaggi della playlist",
    BurgerButton: "Hamburger",
    LinkButton: "Collegamento",
    SearchButton: "Ricerca",
    AdministerPlaylist: "Amministrazione playlist",
    NoSearchResults: "Nessun risultato della ricerca corrisponde alla query.",
    DefaultCDNLabel: "Seleziona origine apprendimento",
    DefaultCDNDescription: "Selezionare un'origine alternativa per il contenuto di apprendimento.",
    DescriptionFieldLabel: "Campo descrizione",
    ImageSelectorLabel: "Scegli un'immagine",
    ImageSelectorButton: "Sceglie immagine",
    DetailEditTitle: "Titolo",
    DetailEditDescription: "Descrizione",
    DetailEditUrl: "Url",
    DetailEditCategory: "Categoria",
    DetailEditCategoryNoData: "Non sono disponibili categorie",
    DetailEditTechnology: "Tecnologia",
    DetailEditLevel: "Livello",
    DetailEditAudience: "Gruppo di destinatari",
    AssetSearchPlaceHolderLabel: "Cerca risorse esistenti",
    CategoryHeading: "Aggiungi nuova sottocategoria",
    CategoryHeadingLabel: "Sottocategoria",
    CategoryPlaylistSavedMessage: "La playlist è stata salvata.",
    CategoryPlaylistSaveFailedMessage: "Non è stato possibile salvare la playlist.",
    CategoryNewPlayListMessage: "Sono state apportate modifiche a una nuova playlist. Eliminare le modifiche e continuare?",
    CategoryEditedPlayListMessage: "Sono state apportate modifiche a questa playlist. Eliminare le modifiche e continuare?",
    PlaylistEditAssetSavedMessage: "La risorsa è stata salvata.",
    PlaylistEditAssetSaveFailedMessage: "Non è stato possibile salvare la risorsa.",
    PlaylistEditCreatePlaylistHeader: "Crea una nuova playlist",
    PlaylistEditPlaylistDetailsHeader: "Dettagli della playlist: ",
    PlaylistEditPlaylistAssetsHeader: "Risorse della playlist",
    PlaylistEditEditLabel: "Modifica dettagli",
    PlaylistEditSaveLabel: "Salva dettagli",
    PlaylistEditCancelLabel: "Annulla dettagli",
    PlaylistEditCloseLabel: "Chiudi playlist",
    AssetDetailsCreateHeader: "Crea una nuova risorsa",
    AssetDetailsManageHeader: "Gestire una risorsa personalizzata:",
    AssetDetailsDetailsHeader: "Dettagli risorsa: ",
    AssetDetailsSaveLabel: "Salva risorsa",
    AssetDetailsCancelLabel: "Annulla risorsa",
    AssetDetailsCloseLabel: "Chiudi risorsa",
    AssetDetailsOpenPage: "Apri pagina",
    TechnologyHeadingLabel: "Tecnologia",
    SubcategoryHeadingLabel: "Intestazione sottocategoria",
    PlaylistItemPlaylistHeadingLabel: "Playlist",
    PlaylistItemPlaylistDelete: "Elimina playlist",
    PlaylistEditAssetNewLabel: "Nuova risorsa",
    PlaylistRemove: "Rimuovi dalla playlist",
    ImageSelectorImageAlt: "Playlist personalizzata",
    ImageSelectorUrlPlaceholder: "URL immagine",
    CategoryHeadingAddPlaylistToSubcategory: "Aggiungi una nuova playlist alla sottocategoria",
    AdminMenuTechnologyLabel: "Tecnologia",
    AdminMenuCategoryLabel: "Categoria",
    Show: "Mostra",
    Hide: "Nascondi",
    Add: "Aggiungi",
    Edit: "Modifica",
    CloseButton: "Chiudi",
    EditButton: "Modifica",
    StepButton: "Passaggio",
    MoveUpButton: "Spostamento verso l'alto",
    MoveDownButton: "Spostamento verso il basso",
    SaveButton: "Salva",
    CancelButton: "Annulla",
    UpdateButton: "Aggiorna",
    DeleteButton: "Elimina",
    DetailEditNewPageMessage: "Nuova pagina risorsa nella raccolta pagine del sito.",
    DetailEditExistingPageMessage: "Immettere l'URL di una pagina esistente.",
    DetailEditNewPageButton: "Crea pagina risorsa",
    DetailEditExistingPageButton: "Immetti URL",
    AdminAddCdnLabel: "Aggiungi pacchetto di contenuto",
    AdminEditCdnLabel: "Modifica pacchetto di contenuto",
    AdminDeleteCdnLabel: "Elimina pacchetto di contenuto",
    AdminCdnIdLabel: "ID pacchetto di contenuto/ID partner",
    AdminCdnDisplayName: "Nome visualizzato",
    AdminCdnBaseUrl: "URL di base",
    AdminCustomCdnTitle: "Pacchetto di contenuto personalizzato",
    AdminCustomCdnDescription: "I pacchetti di contenuto personalizzati sono una caratteristica avanzata e devono essere usati solo dagli amministratori con esperienza di amministrazione del contenuto Web. Origini di contenuto non attendibili possono introdurre contenuti non sicuri nel sito. È consigliabile aggiungere solo origini attendibili. Per altre informazioni, vedere la Guida per i partner nella documentazione sui percorsi di apprendimento.",
    AdminConfirmContentPack: "È stata avviata una nuova scheda del browser che consente di eseguire il provisioning del nuovo pacchetto di contenuto. Al termine, fare clic su \"Completa\" di seguito per aggiornare l'elenco di contenuti alternativi. Se si verifica un errore o si sceglie di non installare il pacchetto di contenuto, fare clic su 'Annulla'. È possibile tornare in qualsiasi momento.",
    AdminCdnCompleteButton: "Completa",
    AdminCdnCancelButton: "Annulla",
    AdminCdnSaveButton: "Salva",
    AdminCdnUpdateButton: "Aggiorna",
    AdminRemoveCdn: "Confermare che si vuole rimuovere il CDN selezionato.",
    AdminAbout: "Informazioni sulla web part",
    DocumentationLinkLabel: "Documentazione sui percorsi di apprendimento di M365",
    CategoryCopyPlaylistFail: "Non è stato possibile copiare la playlist. Contattare l'amministratore o consultare la console del browser per altre informazioni.",
    PlaylistEditCopyLabel: "Copia playlist",
    PlaylistNext: "Avanti",
    PlaylistPrevious: "Indietro",
    PlaylistFullScreen: "Attiva o disattiva modalità schermo intero",
    FilterNotSet: "Tutti",
    AdminVersionUpdateNotice: "La web part dei percorsi di apprendimento di Microsoft 365 installata non è aggiornata. La versione attualmente in uso è %0% e la versione più recente è %1%.",
    AdminVersionUpdateInstructions: "Consultare le istruzioni per l''Aggiornamento della soluzione'.",
    AdminSecurityMessage: "Non si hanno i diritti per amministrare i percorsi di apprendimento di Microsoft 365. Rivolgersi all'amministratore per partecipare al gruppo proprietari o membri.",
    AdminConfigIssueMessage: "I percorsi di apprendimento di Microsoft 365 hanno un problema di configurazione. Per assistenza, rivolgersi all'amministratore. [Amministratori: Consultare la console del browser per i registri dettagliati. Per assistenza tecnica, vedere l'elenco dei problemi su https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "Url: In attesa del titolo...",
    CreatingPage: "Creazione pagina",
    TryAgain: "Riprova",
    AddLanguagePlaceholder: "Aggiungi lingua",
    NotApplicable: "Non applicabile",
    DataUpgradeTitle: "Aggiornamento dei dati da",
    DataUpgradeIntro: "È stato eseguito l'aggiornamento a una nuova versione principale dei percorsi di apprendimento di Microsoft 365. Per avviare il processo di aggiornamento, premere 'Avvia'",
    DataUpgradeStart: "Avvia",
    DataUpgradeClose: "Chiudi",
    DataUpgradeIssue: "Se si verificano problemi durante l'aggiornamento, è possibile richiedere assistenza segnalando il problema nell' ",
    DataUpgradeIssueLink: "elenco problemi GitHub dei percorsi di apprendimento di Microsoft 365",
    DataUpgradeLog: "Log dell'aggiornamento",
    DataUpgradeComplete: "L'aggiornamento è stato completato.",
    DataUpgradeErrors: "Errori",
    LogLevel: "Livello",
    LogMessage: "Messaggio",
    AboutGroupHeader: "Percorsi di apprendimento di M365",
    AboutGroupTitle: "Configurazione corrente*",
    AboutGroupTitle2: "(* sarà specifico per il pacchetto di contenuto corrente)",
    AboutLearningSiteUrl: "URL del sito di apprendimento:",
    AboutBaseCDNPath: "Percorso CDN di base:",
    AboutTelemetryStatus: "Stato telemetria:",
    AboutCurrentWPVersion: "Versione della web part corrente:",
    AboutMultilingualEnabled: "Pagine multilingue abilitate:",
    AboutMultilingualLanguages: "Lingue di traduzione delle pagine multilingue:",
    AboutConfiguredLanguages: "Lingue configurate:",
    AboutSupportedLanguages: "Lingue supportate dal pacchetto di contenuto:",
    AboutDefaultSiteLanguage: "Lingua del sito predefinita:",
    AboutCurrentUserLanguage: "Lingua utente corrente:",
    AboutContentPackAssetOrigins: "Origini delle risorse del pacchetto di contenuto:",
    AboutCurrentCDN: "Rete CDN corrente:",
    AboutAllCDNs: "Tutte le reti CDN:",
    AboutCacheLastUpdate: "Ultimo aggiornamento della cache:",
    DocumentLibraries: "Raccolte documenti",
    OpenButtonLabel: "Apri",
    CancelButtonLabel: "Annulla",
    UploadFileHeader: "Carica file",
    ChangeFileLinkLabel: "Modifica file",
    ChooseFileLinkLabel: "Scegli file",
    AddFileButtonLabel: "Aggiungi file",
    WebSearchLinkLabel: "Ricerca sul Web",
    CreativeCommonsMessage: "Questi risultati sono contrassegnati con licenze Creative Commons. Controllare le licenze per garantire la conformità.",
    CopyrightWarning: "Sei responsabile del rispetto dei diritti degli altri utenti, incluso il copyright.",
    CopyrightUrl: "https://www.microsoft.com/it-IT/legal/copyright/default.aspx",
    LearnMoreLink: "Altre informazioni.",
    NoResultsBadEnglish: "***Non è stato trovato alcun risultato. Provare a modificare le opzioni del filtro",
    SearchResultAlt: "Risultato immagine per {0}.",
    SearchResultAriaLabel: "Premere INVIO per aprire l'origine immagine in una nuova scheda.",
    SearchBoxPlaceholder: "Ricerca sul Web",
    PoweredByBing: "Powered by Bing",
    SizeOptionAll: "Tutti",
    SizeOptionExtraLarge: "Dimensioni molto grandi",
    SizeOptionLarge: "Grandi dimensioni",
    SizeOptionMedium: "Medio",
    SizeOptionSmall: "Piccole dimensioni",
    LayoutOptionAll: "Tutti",
    LayoutOptionSquare: "Quadrato",
    LayoutOptionTall: "Alto",
    LayoutOptionWide: "Largo",
    LicenseOptionAll: "Tutti",
    LicenseOptionAny: "Solo Creative Commons",
    RecentDocumentsHeader: "Documenti recenti",
    Loading: "Caricamento in corso...",
    NoRecentFiles: "Nessun file recente",
    NoRecentFilesDescription: "Provare a selezionare un file dal sito o caricarne uno dal dispositivo.",
    EditedByNamePlate: "modificato da ",
    LinkHeader: "Da un collegamento",
    LinkFileInstructions: "Incollare un collegamento a un file in OneDrive for Business o SharePoint Online",
    NoExternalLinksValidationMessage: "Supportiamo solo il collegamento ai file nella propria organizzazione.",
    ProvidedValueIsInvalid: "Il valore specificato non è valido",
    ImageAriaLabelTemplate: "Immagine .{0}",
    DocumentLabelTemplate: "{0}, documento, modificato {1}, modificato da {2}, privato",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, cartella, modificato {1}, modificato da {2}, {3} elementi, privato",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 byte",
    SizeUnit: [
      "byte",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Selezione file",
    OrgAssetsTabLabel: "Immagini e file forniti dall'organizzazione",
    RecentLinkLabel: "Recenti",
    SiteLinkLabel: "Sito",
    UploadLinkLabel: "Carica",
    FromLinkLinkLabel: "Da un collegamento",
    TypeAriaLabel: "Operazioni su colonne per tipo di file. Premere per ordinare per tipo di file",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Cartella",
    ImageAltText: "Immagine .{0}",
    NameField: "Nome",
    SortedAscending: "Ordinati dalla A alla Z",
    SortedDescending: "Ordinati dalla Z alla A",
    ModifiedField: "Data modifica",
    ModifiedByField: "Autore modifica",
    FileSizeField: "Dimensione file",
    OneDriveEmptyFolderAlt: "Svuota cartella",
    OneDriveEmptyFolderDescription: "Per aggiungere file, passare a OneDrive. È anche possibile aggiungere file in questa cartella con l'app OneDrive per il computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Questa cartella è vuota",
    ListLayoutAriaLabel: "Opzioni di visualizzazione. {0}  {1} .",
    ListLayoutCompact: "Visualizzazione compatta",
    ListLayoutCompactDescription: "Visualizza elementi e dettagli in un elenco compatto",
    ListLayoutList: "Visualizzazione elenco",
    ListLayoutListDescription: "Visualizza elementi e dettagli in un elenco",
    ListLayoutTile: "Visualizzazione affiancata",
    ListLayoutTileDescription: "Visualizzare elementi con riquadri di anteprima",
    ListOptionsAlt: "Opzioni di visualizzazione. {0} selezionata.",
    ListOptionsTitle: "Aprire il menu delle opzioni di visualizzazione",
    Selected: "selezionato",
    CategoryTranslationNotAvailable: "Una traduzione della sottocategoria selezionata non è disponibile per questa lingua.",
    Abandoned: "Abbandonato",
    AbandonedPlaylist: "Playlist",
    RemoveLanguageLabel: "Rimuovere lingua",
    PropertyPaneNone: "nessuno",
    WebPartModeFull: "Completo",
    WebPartModeContentOnly: "Solo contenuto",
    PropertyPaneFilterCategory: "Categoria",
    PropertyPaneFilterSubCategory: "Sottocategoria",
    PropertyPaneFilterPlaylist: "Playlist",
    AdminSavingNotification: "Salvataggio...",
    DataUpgradeReview: "Revisione",
    DataUpgradeMultilingual: "Il supporto multilingue è abilitato per i percorsi di apprendimento. Controlla le lingue abilitate per il tuo sito e disattiva le lingue che non desideri supportare.",
    M365Title: "Percorsi di apprendimento di Microsoft 365",
    ValidateBase: "The base url for the CDN must end in a (/).",
    CustomizeSort: "Customize Sort",
    ResetSort: "Reset Sort"
  };
});