declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Web パーツ タイトル (コンテンツのみモード)",
    LPViewerPropertyDescription: "カスタム学習プロパティ",
    LPViewerPropertyGroupName: "既定のビュー",
    WebpartModeLabel: "Web パーツ モードを選択する",
    WebpartModeDescription: "Web パーツの表示方法",
    ShowNavigationLabel: "カスタム学習ナビゲーション ヘッダーを表示する",
    DefaultFilterLabel: "フィルターを選択する",
    DefaultFilterDescription: "結果を絞り込むフィルターを選択します。一度に 1 つの種類のみ、フィルター処理できます。",
    DefaultCategoryLabel: "カテゴリにフィルターを適用する",
    DefaultCategoryDescription: "結果を絞り込むカテゴリを選択します。",
    DefaultSubCategoryLabel: "サブカテゴリにフィルターを適用する",
    DefaultSubCategoryDescription: "結果を絞り込むサブカテゴリを選択します。",
    DefaultPlaylistLabel: "再生リストにフィルターを適用する",
    DefaultPlaylistDescription: "結果を絞り込むカテゴリを選択します。",
    DefaultAssetLabel: "資産を選択する",
    DefaultAssetDescription: "再生リストから表示する資産を選択します。",
    FilterPanelHeader: "最適なコースを選択する",
    FilterPanelAudienceLabel: "私は",
    FilterPanelSkillsetLabel: "自分のスキル セットは",
    NavigationHome: "ホーム",
    SearchResultItemPlayListLabel: "再生リスト:",
    SearchResultItemCategoryLabel: "カテゴリ:",
    SearchPanelPlaceHolderLabel: "再生リストまたは資産を検索",
    LinkPanelCopyLabel: "コピー",
    HeaderPlaylistPanelCurrentPlaylistLabel: "現在の再生リスト:",
    HeaderPlaylistPanelAdminHeader: "管理",
    PlaylistOverviewDesignMessage: "使用中、この領域には、表示されている再生リスト内の他の資産が表示されます。",
    PlaylistOverviewHeading: "再生リストのすべての手順",
    BurgerButton: "バーガー",
    LinkButton: "リンク",
    SearchButton: "検索",
    AdministerPlaylist: "再生リストの管理",
    NoSearchResults: "検索結果がクエリと一致しません。",
    DefaultCDNLabel: "学習ソースを選択する",
    DefaultCDNDescription: "学習コンテンツの代替ソースを選択します。",
    DescriptionFieldLabel: "説明フィールド",
    ImageSelectorLabel: "画像を選択する",
    ImageSelectorButton: "画像を選択する",
    DetailEditTitle: "タイトル",
    DetailEditDescription: "説明",
    DetailEditUrl: "Url",
    DetailEditCategory: "カテゴリ",
    DetailEditCategoryNoData: "使用できるカテゴリはありません",
    DetailEditTechnology: "テクノロジ",
    DetailEditLevel: "レベル",
    DetailEditAudience: "対象ユーザー",
    AssetSearchPlaceHolderLabel: "既存の資産を検索する",
    CategoryHeading: "新しい下位カテゴリを追加する",
    CategoryHeadingLabel: "下位カテゴリ",
    CategoryPlaylistSavedMessage: "再生リストが保存されました。",
    CategoryPlaylistSaveFailedMessage: "再生リストを保存できませんでした。",
    CategoryNewPlayListMessage: "新しい再生リストを変更しました。変更を破棄して続行しますか?",
    CategoryEditedPlayListMessage: "この再生リストを変更しました。変更を破棄して続行しますか?",
    PlaylistEditAssetSavedMessage: "資産が保存されました。",
    PlaylistEditAssetSaveFailedMessage: "資産を保存できませんでした。",
    PlaylistEditCreatePlaylistHeader: "新しい再生リストを作成する",
    PlaylistEditPlaylistDetailsHeader: "再生リストの詳細:",
    PlaylistEditPlaylistAssetsHeader: "再生リストの資産",
    PlaylistEditEditLabel: "詳細を編集する",
    PlaylistEditSaveLabel: "詳細を保存する",
    PlaylistEditCancelLabel: "詳細をキャンセルする",
    PlaylistEditCloseLabel: "再生リストを閉じる",
    AssetDetailsCreateHeader: "新しい資産を作成する",
    AssetDetailsManageHeader: "カスタム資産の管理:",
    AssetDetailsDetailsHeader: "資産の詳細:",
    AssetDetailsSaveLabel: "資産を保存する",
    AssetDetailsCancelLabel: "資産をキャンセルする",
    AssetDetailsCloseLabel: "資産を閉じる",
    AssetDetailsOpenPage: "ページを開く",
    TechnologyHeadingLabel: "テクノロジ",
    SubcategoryHeadingLabel: "下位カテゴリの見出し",
    PlaylistItemPlaylistHeadingLabel: "再生リスト",
    PlaylistItemPlaylistDelete: "再生リストを削除する",
    PlaylistEditAssetNewLabel: "新しい資産",
    PlaylistRemove: "再生リストから削除する",
    ImageSelectorImageAlt: "カスタム再生リスト",
    ImageSelectorUrlPlaceholder: "イメージ Url",
    CategoryHeadingAddPlaylistToSubcategory: "新しい再生リストを下位カテゴリに追加する",
    AdminMenuTechnologyLabel: "テクノロジ",
    AdminMenuCategoryLabel: "カテゴリ",
    Show: "表示",
    Hide: "非表示",
    Add: "追加",
    Edit: "編集",
    CloseButton: "閉じる",
    EditButton: "編集",
    StepButton: "手順",
    MoveUpButton: "上に移動",
    MoveDownButton: "下に移動",
    SaveButton: "保存",
    CancelButton: "キャンセル",
    UpdateButton: "更新する",
    DeleteButton: "削除",
    DetailEditNewPageMessage: "サイト ページ ライブラリの新しい資産ページ。",
    DetailEditExistingPageMessage: "既存ページの URL を入力します。",
    DetailEditNewPageButton: "資産ページを作成する",
    DetailEditExistingPageButton: "Url を入力する",
    AdminAddCdnLabel: "コンテンツ パックを追加する",
    AdminEditCdnLabel: "コンテンツ パックを編集する",
    AdminDeleteCdnLabel: "コンテンツ パックを削除する",
    AdminCdnIdLabel: "コンテンツ パック ID/パートナー ID",
    AdminCdnDisplayName: "表示名",
    AdminCdnBaseUrl: "ベース URL",
    AdminCustomCdnTitle: "カスタム コンテンツ パック",
    AdminCustomCdnDescription: "カスタム コンテンツ パックは、高度な機能です。Web コンテンツの管理経験のある管理者だけが使用してください。信頼できないコンテンツ ソースにより、サイトに安全でないコンテンツが取り込まれる場合があります。信頼できるソースのみを追加する必要があります。詳細については、「学習経路の文書化のパートナー ガイダンス」」を参照してください。",
    AdminConfirmContentPack: "新しいコンテンツ パックをプロビジョニングできる新しいブラウザー タブが開始されました。正常に完了したら、下の [完了] をクリックして代替コンテンツ リストを更新します。エラーがある場合、またはコンテンツ パックをインストールしない場合は、[キャンセル] をクリックしてください。いつでも戻ることができます。",
    AdminCdnCompleteButton: "完了",
    AdminCdnCancelButton: "キャンセル",
    AdminCdnSaveButton: "保存",
    AdminCdnUpdateButton: "更新する",
    AdminRemoveCdn: "選択されている CDN を削除しますか?",
    AdminAbout: "Web パーツについて",
    DocumentationLinkLabel: "M365 の学習経路の文書を開く",
    CategoryCopyPlaylistFail: "再生リストをコピーできませんでした。詳細については、管理者にお問い合わせるか、ブラウザー コンソールを参照してください。",
    PlaylistEditCopyLabel: "再生リストをコピーする",
    PlaylistNext: "次へ",
    PlaylistPrevious: "前へ",
    PlaylistFullScreen: "全画面表示モードを切り替える",
    FilterNotSet: "すべて",
    AdminVersionUpdateNotice: "インストールされている Microsoft 365 の学習経路 Web パーツは最新ではありません。現在、バージョン %0% を実行しており、最新バージョンは %1% です。",
    AdminVersionUpdateInstructions: "「ソリューションの更新」の手順を参照してください。",
    AdminSecurityMessage: "Microsoft 365の学習経路を管理する権限がありません。所有者またはメンバー グループへの参加について管理者に相談してください。",
    AdminConfigIssueMessage: "Microsoft 365 の学習経路には構成の問題があります。管理者に問い合わせてください。[管理者:詳細なログについては、ブラウザー コンソールをご覧ください。技術サポートについては、https://github.com/pnp/custom-learning-office-365/issues の問題の一覧をご確認ください。]",
    AdminAwaitingUrlPrompt: "Url:タイトルを待っています...",
    CreatingPage: "ページを作成する",
    TryAgain: "もう一度お試しください",
    AddLanguagePlaceholder: "言語の追加",
    NotApplicable: "該当なし",
    DataUpgradeTitle: "データのアップグレード",
    DataUpgradeIntro: "Microsoft 365 の学習経路をメジャーな新しいリリースに更新しました。アップグレード プロセスを開始するには、[開始] を押します。",
    DataUpgradeStart: "開始",
    DataUpgradeClose: "閉じる",
    DataUpgradeIssue: "アップデートの実行中に問題が発生した場合は、Microsoft 365 の学習経路 GitHub の問題リストに ",
    DataUpgradeIssueLink: "問題を送信してサポートを依頼できます。",
    DataUpgradeLog: "アップグレード ログ",
    DataUpgradeComplete: "アップグレードが完了しました。",
    DataUpgradeErrors: "エラー",
    LogLevel: "レベル",
    LogMessage: "メッセージ",
    AboutGroupHeader: "M365 の学習経路",
    AboutGroupTitle: "現在の構成*",
    AboutGroupTitle2: "(* は現在のコンテンツ パック固有のものです)",
    AboutLearningSiteUrl: "学習サイトの Url:",
    AboutBaseCDNPath: "ベース CDN パス:",
    AboutTelemetryStatus: "テレメトリの状態:",
    AboutCurrentWPVersion: "現在の Web パーツのバージョン:",
    AboutMultilingualEnabled: "多言語ページの有効化:",
    AboutMultilingualLanguages: "多言語ページの翻訳言語:",
    AboutConfiguredLanguages: "構成された言語:",
    AboutSupportedLanguages: "コンテンツパックでサポートされる言語:",
    AboutDefaultSiteLanguage: "既定のサイトの言語:",
    AboutCurrentUserLanguage: "現在のユーザーの言語:",
    AboutContentPackAssetOrigins: "コンテンツ パックの資産の元:",
    AboutCurrentCDN: "現在の CDN:",
    AboutAllCDNs: "すべての CDN:",
    AboutCacheLastUpdate: "キャッシュの最終更新日:",
    DocumentLibraries: "ドキュメント ライブラリ",
    OpenButtonLabel: "開く",
    CancelButtonLabel: "キャンセル",
    UploadFileHeader: "ファイルをアップロードする",
    ChangeFileLinkLabel: "ファイルを変更する",
    ChooseFileLinkLabel: "ファイルを選択する",
    AddFileButtonLabel: "ファイルを追加する",
    WebSearchLinkLabel: "Web 検索",
    CreativeCommonsMessage: "これらの結果には Creative Commons ライセンスがタグ付けされています。ライセンスを確認し、準拠していることを確認します。",
    CopyrightWarning: "著作権など他人の権利を尊重する責任があります。",
    CopyrightUrl: "https://www.microsoft.com/ja-JP/legal/copyright/default.aspx",
    LearnMoreLink: "詳細については、こちらを参照してください。",
    NoResultsBadEnglish: "***該当する結果はありません。フィルター オプションの変更を試す",
    SearchResultAlt: "{0} 件の画像結果。",
    SearchResultAriaLabel: "Enter キーを押して、新しいタブで画像ソースを開きます。",
    SearchBoxPlaceholder: "Web 検索",
    PoweredByBing: "Bing 提供",
    SizeOptionAll: "すべて",
    SizeOptionExtraLarge: "巨大",
    SizeOptionLarge: "大",
    SizeOptionMedium: "中",
    SizeOptionSmall: "小",
    LayoutOptionAll: "すべて",
    LayoutOptionSquare: "正方形",
    LayoutOptionTall: "高い",
    LayoutOptionWide: "広い",
    LicenseOptionAll: "すべて",
    LicenseOptionAny: "Creative Commons のみ",
    RecentDocumentsHeader: "最近使用したドキュメント",
    Loading: "読み込み中...",
    NoRecentFiles: "最近使ったファイルはありません",
    NoRecentFilesDescription: "サイトでファイルを選択するか、デバイスからファイルをアップロードしてください。",
    EditedByNamePlate: "編集者 ",
    LinkHeader: "リンクから",
    LinkFileInstructions: "OneDrive for Business または SharePoint Online のファイルへのリンクを貼り付ける",
    NoExternalLinksValidationMessage: "組織内のファイルへのリンクのみをサポートします。",
    ProvidedValueIsInvalid: "指定した値は無効です。",
    ImageAriaLabelTemplate: ".{0} 件の画像",
    DocumentLabelTemplate: "{0}、ドキュメント、修正済み {1}、{2} によって編集、非公開",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}、フォルダー、修正済み {1}、{2} によって編集、{3} 件のアイテム、非公開",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 バイト",
    SizeUnit: [
      "バイト",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "ファイル ピッカー",
    OrgAssetsTabLabel: "組織から提供される画像とファイル",
    RecentLinkLabel: "最近使った項目",
    SiteLinkLabel: "サイト",
    UploadLinkLabel: "アップロード",
    FromLinkLinkLabel: "リンクから",
    TypeAriaLabel: "ファイルの種類の列の操作、押してファイルの種類を並べ替える",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "フォルダー",
    ImageAltText: ".{0} 件の画像",
    NameField: "名前",
    SortedAscending: "昇順で並べ替え",
    SortedDescending: "降順で並べ替え",
    ModifiedField: "更新日時",
    ModifiedByField: "変更者",
    FileSizeField: "ファイル サイズ",
    OneDriveEmptyFolderAlt: "フォルダーを空にする",
    OneDriveEmptyFolderDescription: "ファイルを追加するには、OneDrive に移動します。コンピューター用の OneDrive アプリを使用して、このフォルダーにファイルを追加することもできます。",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "このフォルダーは空です",
    ListLayoutAriaLabel: "表示オプション。{0}  {1}。",
    ListLayoutCompact: "コンパクト表示",
    ListLayoutCompactDescription: "コンパクト リスト内のアイテムと詳細を表示する",
    ListLayoutList: "リスト ビュー",
    ListLayoutListDescription: "リスト内のアイテムと詳細を表示する",
    ListLayoutTile: "タイル ビュー",
    ListLayoutTileDescription: "タイル プレビューでアイテムを表示する",
    ListOptionsAlt: "表示オプション。{0} 件が選択されました。",
    ListOptionsTitle: "表示オプション メニューを開く",
    Selected: "選択されました",
    CategoryTranslationNotAvailable: "選択した下位カテゴリの翻訳は、この言語では使用できません。",
    Abandoned: "中止",
    AbandonedPlaylist: "再生リスト",
    RemoveLanguageLabel: "言語を削除する",
    PropertyPaneNone: "なし",
    WebPartModeFull: "完全",
    WebPartModeContentOnly: "コンテンツのみ",
    PropertyPaneFilterCategory: "カテゴリ",
    PropertyPaneFilterSubCategory: "サブカテゴリ",
    PropertyPaneFilterPlaylist: "再生リスト",
    AdminSavingNotification: "保存中..",
    DataUpgradeReview: "レビュー",
    DataUpgradeMultilingual: "多国語サポートはラーニング パスに対して有効になっています。サイトで有効になっている言語を確認し、サポートの必要がない言語をオフにします。",
    M365Title: "Microsoft 365 学習経路",
    ValidateBase: "The base url for the CDN must end in a (/).",
    CustomizeSort: "Customize Sort",
    ResetSort: "Reset Sort"
  };
});