declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Titel van webonderdeel (modus Alleen inhoud)",
    LPViewerPropertyDescription: "Eigenschappen voor aangepast leren",
    LPViewerPropertyGroupName: "Standaardweergave",
    WebpartModeLabel: "Modus voor webonderdeel selecteren",
    WebpartModeDescription: "Hoe wilt u het webonderdeel weergeven",
    ShowNavigationLabel: "Koptekst voor aangepast leren weergeven",
    DefaultFilterLabel: "Filter selecteren",
    DefaultFilterDescription: "Selecteer een filter om de resultaten te beperken. U kunt maar op één type tegelijk filteren.",
    DefaultCategoryLabel: "Filteren op categorie",
    DefaultCategoryDescription: "Selecteer een categorie om de resultaten te beperken.",
    DefaultSubCategoryLabel: "Filteren op subcategorie",
    DefaultSubCategoryDescription: "Selecteer een subcategorie om de resultaten te beperken.",
    DefaultPlaylistLabel: "Filteren op afspeellijst",
    DefaultPlaylistDescription: "Selecteer een categorie om de resultaten te beperken.",
    DefaultAssetLabel: "Asset selecteren",
    DefaultAssetDescription: "Selecteer een asset om weer te geven uit de afspeellijst.",
    FilterPanelHeader: "Kies de gewenste cursussen",
    FilterPanelAudienceLabel: "Ik ben een",
    FilterPanelSkillsetLabel: "Mijn vaardigheden",
    NavigationHome: "Home",
    SearchResultItemPlayListLabel: "Afspeellijst: ",
    SearchResultItemCategoryLabel: "Categorie: ",
    SearchPanelPlaceHolderLabel: "Zoeken naar afspeellijsten of assets",
    LinkPanelCopyLabel: "Kopiëren",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Huidige afspeellijst: ",
    HeaderPlaylistPanelAdminHeader: "Beheer",
    PlaylistOverviewDesignMessage: "Tijdens gebruik worden hier andere assets weergegeven uit de afspeellijst die wordt weergegeven.",
    PlaylistOverviewHeading: "Alle stappen in afspeellijst",
    BurgerButton: "Burger",
    LinkButton: "Koppeling",
    SearchButton: "Zoeken",
    AdministerPlaylist: "Beheer van afspeellijsten",
    NoSearchResults: "Geen zoekresultaten gevonden voor de zoekopdracht.",
    DefaultCDNLabel: "Leerbron selecteren",
    DefaultCDNDescription: "Selecteer een alternatieve bron voor leermateriaal.",
    DescriptionFieldLabel: "Veld Beschrijving",
    ImageSelectorLabel: "Een afbeelding kiezen",
    ImageSelectorButton: "Afbeelding kiezen",
    DetailEditTitle: "Titel",
    DetailEditDescription: "Beschrijving",
    DetailEditUrl: "Url",
    DetailEditCategory: "Categorie",
    DetailEditCategoryNoData: "Geen categorieën beschikbaar",
    DetailEditTechnology: "Technologie",
    DetailEditLevel: "Niveau",
    DetailEditAudience: "Doelgroep",
    AssetSearchPlaceHolderLabel: "Zoeken naar bestaande assets",
    CategoryHeading: "Nieuwe subcategorie toevoegen",
    CategoryHeadingLabel: "Subcategorie",
    CategoryPlaylistSavedMessage: "De afspeellijst is opgeslagen.",
    CategoryPlaylistSaveFailedMessage: "Kan de afspeellijst niet opslaan.",
    CategoryNewPlayListMessage: "U hebt een nieuwe afspeellijst gewijzigd. Wilt u de wijzigingen weggooien en doorgaan?",
    CategoryEditedPlayListMessage: "U hebt deze afspeellijst gewijzigd. Wilt u de wijzigingen weggooien en doorgaan?",
    PlaylistEditAssetSavedMessage: "Asset is opgeslagen.",
    PlaylistEditAssetSaveFailedMessage: "Kan asset niet opslaan.",
    PlaylistEditCreatePlaylistHeader: "Een nieuwe afspeellijst maken",
    PlaylistEditPlaylistDetailsHeader: "Details van afspeellijst: ",
    PlaylistEditPlaylistAssetsHeader: "Assets van afspeellijst",
    PlaylistEditEditLabel: "Detail bewerken",
    PlaylistEditSaveLabel: "Detail opslaan",
    PlaylistEditCancelLabel: "Detail annuleren",
    PlaylistEditCloseLabel: "Afspeellijst sluiten",
    AssetDetailsCreateHeader: "Een nieuwe asset maken",
    AssetDetailsManageHeader: "Aangepaste asset beheren:",
    AssetDetailsDetailsHeader: "Details van asset: ",
    AssetDetailsSaveLabel: "Asset opslaan",
    AssetDetailsCancelLabel: "Asset annuleren",
    AssetDetailsCloseLabel: "Asset sluiten",
    AssetDetailsOpenPage: "Pagina openen",
    TechnologyHeadingLabel: "Technologie",
    SubcategoryHeadingLabel: "Kop van subcategorie",
    PlaylistItemPlaylistHeadingLabel: "Afspeellijst",
    PlaylistItemPlaylistDelete: "Afspeellijst verwijderen",
    PlaylistEditAssetNewLabel: "Nieuwe asset",
    PlaylistRemove: "Verwijderen uit afspeellijst",
    ImageSelectorImageAlt: "Aangepaste afspeellijst",
    ImageSelectorUrlPlaceholder: "Afbeeldings-Url",
    CategoryHeadingAddPlaylistToSubcategory: "Nieuwe afspeellijst toevoegen aan subcategorie",
    AdminMenuTechnologyLabel: "Technologie",
    AdminMenuCategoryLabel: "Categorie",
    Show: "Weergeven",
    Hide: "Verbergen",
    Add: "Toevoegen",
    Edit: "Bewerken",
    CloseButton: "Sluiten",
    EditButton: "Bewerken",
    StepButton: "Stap",
    MoveUpButton: "Omhoog",
    MoveDownButton: "Omlaag",
    SaveButton: "Opslaan",
    CancelButton: "Annuleren",
    UpdateButton: "Bijwerken",
    DeleteButton: "Verwijderen",
    DetailEditNewPageMessage: "Pagina voor nieuwe asset in Site Pages-bibliotheek.",
    DetailEditExistingPageMessage: "Voer de URL in van een bestaande pagina.",
    DetailEditNewPageButton: "Assetpagina maken",
    DetailEditExistingPageButton: "Url invoeren",
    AdminAddCdnLabel: "Inhoudspakket toevoegen",
    AdminEditCdnLabel: "Inhoudspakket bewerken",
    AdminDeleteCdnLabel: "Inhoudspakket verwijderen",
    AdminCdnIdLabel: "Id inhoudspakket/partner-id",
    AdminCdnDisplayName: "Weergavenaam",
    AdminCdnBaseUrl: "Basis-URL",
    AdminCustomCdnTitle: "Aangepast inhoudspakket",
    AdminCustomCdnDescription: "Aangepaste inhoudspakketten vormen een geavanceerde functie en mogen alleen worden gebruikt door beheerders die ervaring hebben met het beheer van webinhoud. Onbetrouwbare inhoudsbronnen kunnen onveilige inhoud introduceren op uw site. Voeg alleen bronnen toe die u vertrouwt. Raadpleeg voor meer informatie de richtlijnen voor partners in de documentatie voor Learning Pathways.",
    AdminConfirmContentPack: "Er is een nieuw browsertabblad geopend waarmee u het nieuwe inhoudspakket kunt inrichten. Wanneer u dit hebt gedaan, klikt u hieronder op Voltooien om de lijst met alternatieve inhoud bij te werken. Als er een fout optreedt of als u besluit het inhoudspakket toch niet te installeren, klikt u op Annuleren. U kunt hier op elk gewenst moment terugkeren.",
    AdminCdnCompleteButton: "Voltooien",
    AdminCdnCancelButton: "Annuleren",
    AdminCdnSaveButton: "Opslaan",
    AdminCdnUpdateButton: "Bijwerken",
    AdminRemoveCdn: "Bevestig dat u de geselecteerde CDN wilt verwijderen?",
    AdminAbout: "Info over webonderdeel",
    DocumentationLinkLabel: "Documentatie over M365 Learning Pathways openen",
    CategoryCopyPlaylistFail: "Het kopiëren van de afspeellijst is mislukt. Neem contact op met de beheerder of bekijk de browserconsole voor meer informatie.",
    PlaylistEditCopyLabel: "Afspeellijst kopiëren",
    PlaylistNext: "Volgende",
    PlaylistPrevious: "Vorige",
    PlaylistFullScreen: "Modus Volledig scherm in- of uitschakelen",
    FilterNotSet: "Alles",
    AdminVersionUpdateNotice: "Het geïnstalleerde webonderdeel Microsoft 365 Learning Pathways is verouderd. U gebruikt momenteel versie %0% en de nieuwste versie is %1%.",
    AdminVersionUpdateInstructions: "Lees de instructies voor het bijwerken van de oplossing.",
    AdminSecurityMessage: "U bent niet gemachtigd om Microsoft 365 Learning Pathways te beheren. Neem contact op met de beheerder om lid te worden van de groep Eigenaren of Leden.",
    AdminConfigIssueMessage: "Er is een configuratieprobleem met Microsoft 365 Learning Pathways. Vraag de beheerder om hulp. [Beheerders: Ga naar de browserconsole voor gedetailleerde logboeken. Bekijk de lijst met problemen op https://github.com/pnp/custom-learning-office-365/issues voor technische ondersteuning.]",
    AdminAwaitingUrlPrompt: "Url: Wachten op titel...",
    CreatingPage: "Bezig met maken van pagina",
    TryAgain: "Probeer het opnieuw",
    AddLanguagePlaceholder: "Taal toevoegen",
    NotApplicable: "Niet van toepassing",
    DataUpgradeTitle: "Gegevens upgraden van",
    DataUpgradeIntro: "U bent bijgewerkt naar een belangrijke nieuwe release van Microsoft 365 Learning Pathways. Druk op Start om te beginnen met het upgradeproces",
    DataUpgradeStart: "Start",
    DataUpgradeClose: "Sluiten",
    DataUpgradeIssue: "Als er problemen zijn bij het uitvoeren van de update, kunt u hulp aanvragen door een probleem toe te voegen aan de ",
    DataUpgradeIssueLink: "lijst met problemen met Microsoft 365 Learning Pathways in GitHub.",
    DataUpgradeLog: "Logboek upgraden",
    DataUpgradeComplete: "De upgrade is voltooid.",
    DataUpgradeErrors: "Fouten",
    LogLevel: "Niveau",
    LogMessage: "Bericht",
    AboutGroupHeader: "M365 Learning Pathways",
    AboutGroupTitle: "Huidige configuratie*",
    AboutGroupTitle2: "(* afhankelijk van het huidige inhoudspakket)",
    AboutLearningSiteUrl: "URL van Learning-site:",
    AboutBaseCDNPath: "Basispad naar CDN:",
    AboutTelemetryStatus: "Telemetriestatus:",
    AboutCurrentWPVersion: "Huidige versie van webonderdeel:",
    AboutMultilingualEnabled: "Meertalige pagina's ingeschakeld:",
    AboutMultilingualLanguages: "Talen voor vertaling voor meertalige pagina's:",
    AboutConfiguredLanguages: "Geconfigureerde talen:",
    AboutSupportedLanguages: "Ondersteunde talen voor inhoudspakket:",
    AboutDefaultSiteLanguage: "Standaardtaal van site:",
    AboutCurrentUserLanguage: "Huidige gebruikerstaal:",
    AboutContentPackAssetOrigins: "Oorsprong van assets inhoudspakket:",
    AboutCurrentCDN: "Huidige CDN:",
    AboutAllCDNs: "Alle CDN's:",
    AboutCacheLastUpdate: "Cache laatst bijgewerkt:",
    DocumentLibraries: "Documentbibliotheken",
    OpenButtonLabel: "Openen",
    CancelButtonLabel: "Annuleren",
    UploadFileHeader: "Bestand uploaden",
    ChangeFileLinkLabel: "Bestand wijzigen",
    ChooseFileLinkLabel: "Bestand kiezen",
    AddFileButtonLabel: "Bestand toevoegen",
    WebSearchLinkLabel: "Zoeken op het web",
    CreativeCommonsMessage: "Deze resultaten worden gelabeld met Creative Commons-licenties. Bekijk de licenties om er zeker van te zijn dat u aan de voorwaarden voldoet.",
    CopyrightWarning: "U bent verantwoordelijk voor het respecteren van de rechten van anderen, inclusief het copyright.",
    CopyrightUrl: "https://www.microsoft.com/nl-nl/legal/copyright/default.aspx",
    LearnMoreLink: "Meer informatie.",
    NoResultsBadEnglish: "***Geen resultaat. Wijzig de filteropties",
    SearchResultAlt: "Afbeeldingsresultaat voor {0}.",
    SearchResultAriaLabel: "Druk op Enter om de bron van de afbeelding in een nieuw tabblad te openen.",
    SearchBoxPlaceholder: "Zoeken op het web",
    PoweredByBing: "Mogelijk gemaakt door Bing",
    SizeOptionAll: "Alles",
    SizeOptionExtraLarge: "Extra groot",
    SizeOptionLarge: "Groot",
    SizeOptionMedium: "Gemiddeld",
    SizeOptionSmall: "Klein",
    LayoutOptionAll: "Alles",
    LayoutOptionSquare: "Vierkant",
    LayoutOptionTall: "Hoog",
    LayoutOptionWide: "Breed",
    LicenseOptionAll: "Alles",
    LicenseOptionAny: "Alleen Creative Commons",
    RecentDocumentsHeader: "Recente documenten",
    Loading: "Laden...",
    NoRecentFiles: "Geen recente bestanden",
    NoRecentFilesDescription: "Selecteer een bestand op uw site of upload een bestand vanaf uw apparaat.",
    EditedByNamePlate: "bewerkt door ",
    LinkHeader: "Via een koppeling",
    LinkFileInstructions: "Plak een koppeling naar een bestand in OneDrive voor Bedrijven of SharePoint Online",
    NoExternalLinksValidationMessage: "We ondersteunen alleen het koppelen naar bestanden in uw eigen organisatie.",
    ProvidedValueIsInvalid: "De opgegeven waarde is ongeldig",
    ImageAriaLabelTemplate: ".{0} Afbeelding",
    DocumentLabelTemplate: "{0}, Document, Gewijzigd {1}, bewerkt door {2}, Privé",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, Map, Gewijzigd {1}, bewerkt door {2}, {3} items, Privé",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 bytes",
    SizeUnit: [
      "bytes",
      "kB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Bestandskiezer",
    OrgAssetsTabLabel: "Afbeeldingen en bestanden verstrekt door uw organisatie",
    RecentLinkLabel: "Recent",
    SiteLinkLabel: "Site",
    UploadLinkLabel: "Uploaden",
    FromLinkLinkLabel: "Via een koppeling",
    TypeAriaLabel: "Kolombewerkingen voor bestandstype, druk om te sorteren op bestandstype",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Map",
    ImageAltText: ".{0} Afbeelding",
    NameField: "Naam",
    SortedAscending: "Gesorteerd van A naar Z",
    SortedDescending: "Gesorteerd van Z naar A",
    ModifiedField: "Gewijzigd op",
    ModifiedByField: "Gewijzigd door",
    FileSizeField: "Bestandsgrootte",
    OneDriveEmptyFolderAlt: "Lege map",
    OneDriveEmptyFolderDescription: "Als u bestanden wilt toevoegen, gaat u naar uw OneDrive. U kunt ook bestanden toevoegen aan deze map met de OneDrive-app voor uw computer.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Deze map is leeg",
    ListLayoutAriaLabel: "Weergaveopties. {0} {1}.",
    ListLayoutCompact: "Compacte weergave",
    ListLayoutCompactDescription: "Items en details weergeven in een compacte lijst",
    ListLayoutList: "Lijstweergave",
    ListLayoutListDescription: "Items en details weergeven in een lijst",
    ListLayoutTile: "Tegelweergave",
    ListLayoutTileDescription: "Items weergeven met tegelvoorbeelden",
    ListOptionsAlt: "Weergaveopties. {0} geselecteerd.",
    ListOptionsTitle: "Het menu Weergaveopties openen",
    Selected: "geselecteerd",
    CategoryTranslationNotAvailable: "Er is voor deze taal geen vertaling beschikbaar van de geselecteerde subcategorie.",
    Abandoned: "Afgebroken",
    AbandonedPlaylist: "Afspeellijsten",
    RemoveLanguageLabel: "Taal verwijderen",
    PropertyPaneNone: "geen",
    WebPartModeFull: "Volledig",
    WebPartModeContentOnly: "Alleen inhoud",
    PropertyPaneFilterCategory: "Categorie",
    PropertyPaneFilterSubCategory: "Subcategorie",
    PropertyPaneFilterPlaylist: "Afspeellijst",
    AdminSavingNotification: "Opslaan...",
    DataUpgradeReview: "Controleren",
    DataUpgradeMultilingual: "Meertalige ondersteuning is ingeschakeld voor leerroutes. Controleer de talen die zijn ingeschakeld voor uw site en schakel de talen uit die u niet wilt ondersteunen.",
    M365Title: "Microsoft 365-leerroutes",
    ValidateBase: "The base url for the CDN must end in a (/).",
    CustomizeSort: "Customize Sort",
    ResetSort: "Reset Sort"
  };
});