declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Título da Web Part (modo somente conteúdo)",
    LPViewerPropertyDescription: "Propriedades de aprendizagem personalizadas",
    LPViewerPropertyGroupName: "Modo de exibição padrão",
    WebpartModeLabel: "Selecione o modo de Web Part",
    WebpartModeDescription: "Como você gostaria de exibir a Web Part?",
    ShowNavigationLabel: "Mostrar o cabeçalho de navegação de aprendizagem personalizado",
    DefaultFilterLabel: "Selecionar um filtro",
    DefaultFilterDescription: "Usar um filtro para limitar os resultados. Você só pode filtrar por um tipo por vez.",
    DefaultCategoryLabel: "Filtrar por categoria",
    DefaultCategoryDescription: "Selecione uma categoria para limitar os resultados.",
    DefaultSubCategoryLabel: "Filtrar por subcategoria",
    DefaultSubCategoryDescription: "Selecione uma subcategoria para limitar os resultados.",
    DefaultPlaylistLabel: "Filtrar para playlist.",
    DefaultPlaylistDescription: "Selecione uma categoria para limitar os resultados.",
    DefaultAssetLabel: "Escolha um ativo",
    DefaultAssetDescription: "Selecione um ativo para exibir na playlist.",
    FilterPanelHeader: "Escolher os cursos que lhe atendem melhor",
    FilterPanelAudienceLabel: "Eu sou um",
    FilterPanelSkillsetLabel: "Minhas habilidades são",
    NavigationHome: "Página inicial",
    SearchResultItemPlayListLabel: "Playlist: ",
    SearchResultItemCategoryLabel: "Categoria: ",
    SearchPanelPlaceHolderLabel: "Pesquisar ativos ou listas de reprodução",
    LinkPanelCopyLabel: "Copiar",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Playlist atual: ",
    HeaderPlaylistPanelAdminHeader: "Administração",
    PlaylistOverviewDesignMessage: "Durante a utilização, esta área mostrará outros ativos na playlist em que ela está sendo exibida.",
    PlaylistOverviewHeading: "Todas as etapas na playlist",
    BurgerButton: "Burger",
    LinkButton: "Link",
    SearchButton: "Pesquisar",
    AdministerPlaylist: "Administração da playlist",
    NoSearchResults: "Nenhum resultado da pesquisa correspondeu à sua consulta.",
    DefaultCDNLabel: "Selecionar fonte de aprendizagem",
    DefaultCDNDescription: "Selecione a fonte alternativa de conteúdo de aprendizagem.",
    DescriptionFieldLabel: "Campo de Descrição",
    ImageSelectorLabel: "Escolher uma imagem",
    ImageSelectorButton: "Escolher imagem",
    DetailEditTitle: "Título",
    DetailEditDescription: "Descrição",
    DetailEditUrl: "Url",
    DetailEditCategory: "Categoria",
    DetailEditCategoryNoData: "Não há categorias disponíveis",
    DetailEditTechnology: "Tecnologia",
    DetailEditLevel: "Nível",
    DetailEditAudience: "Público-alvo",
    AssetSearchPlaceHolderLabel: "Pesquisar ativos existentes",
    CategoryHeading: "Adicionar nova subcategoria",
    CategoryHeadingLabel: "Subcategoria",
    CategoryPlaylistSavedMessage: "A playlist foi salva!",
    CategoryPlaylistSaveFailedMessage: "Falha ao salvar a playlist!",
    CategoryNewPlayListMessage: "Você fez alterações em uma nova playlist. Deseja descartar suas alterações e continuar?",
    CategoryEditedPlayListMessage: "Você fez alterações nesta playlist. Deseja descartar suas alterações e continuar?",
    PlaylistEditAssetSavedMessage: "O ativo foi salvo!",
    PlaylistEditAssetSaveFailedMessage: "Falha ao salvar o ativo!",
    PlaylistEditCreatePlaylistHeader: "Criar uma nova playlist",
    PlaylistEditPlaylistDetailsHeader: "Detalhes da playlist: ",
    PlaylistEditPlaylistAssetsHeader: "Ativos da playlist",
    PlaylistEditEditLabel: "Editar detalhes",
    PlaylistEditSaveLabel: "Salvar detalhes",
    PlaylistEditCancelLabel: "Cancelar detalhes",
    PlaylistEditCloseLabel: "Fechar playlist",
    AssetDetailsCreateHeader: "Criar um novo ativo",
    AssetDetailsManageHeader: "Gerenciar ativo personalizado:",
    AssetDetailsDetailsHeader: "Detalhes do ativo: ",
    AssetDetailsSaveLabel: "Salvar ativo",
    AssetDetailsCancelLabel: "Cancelar ativo",
    AssetDetailsCloseLabel: "Fechar ativo",
    AssetDetailsOpenPage: "Abrir página",
    TechnologyHeadingLabel: "Tecnologia",
    SubcategoryHeadingLabel: "Título da subcategoria",
    PlaylistItemPlaylistHeadingLabel: "Playlist",
    PlaylistItemPlaylistDelete: "Excluir playlist",
    PlaylistEditAssetNewLabel: "Novo ativo",
    PlaylistRemove: "Remover da playlist",
    ImageSelectorImageAlt: "Playlist personalizada",
    ImageSelectorUrlPlaceholder: "URL da Imagem",
    CategoryHeadingAddPlaylistToSubcategory: "Adicionar nova playlist à subcategoria",
    AdminMenuTechnologyLabel: "Tecnologia",
    AdminMenuCategoryLabel: "Categoria",
    Show: "Mostrar",
    Hide: "Ocultar",
    Add: "Adicionar",
    Edit: "Editar",
    CloseButton: "Fechar",
    EditButton: "Editar",
    StepButton: "Etapa",
    MoveUpButton: "Mover para cima",
    MoveDownButton: "Mover para baixo",
    SaveButton: "Salvar",
    CancelButton: "Cancelar",
    UpdateButton: "Atualizar",
    DeleteButton: "Excluir",
    DetailEditNewPageMessage: "Página novo ativo na biblioteca páginas do site.",
    DetailEditExistingPageMessage: "Insira a URL de uma página existente.",
    DetailEditNewPageButton: "Criar página de ativo",
    DetailEditExistingPageButton: "Inserir URL",
    AdminAddCdnLabel: "Adicionar pacote de conteúdo",
    AdminEditCdnLabel: "Editar pacote de conteúdo",
    AdminDeleteCdnLabel: "Excluir pacote de conteúdo",
    AdminCdnIdLabel: "ID de pacote de conteúdo/ID de parceiro",
    AdminCdnDisplayName: "Nome de exibição",
    AdminCdnBaseUrl: "URL base",
    AdminCustomCdnTitle: "Pacote de conteúdo personalizado",
    AdminCustomCdnDescription: "Os pacotes de conteúdo personalizados são um recurso avançado e só devem ser usados por administradores com experiência na administração de conteúdo da Web. Fontes de conteúdo não confiáveis podem apresentar conteúdo não seguro para o seu site. Você só deve adicionar fontes confiáveis. Para saber mais, confira o artigo Diretrizes de Parceria na documentação de caminhos de aprendizagem.",
    AdminConfirmContentPack: "Uma nova guia do navegador foi iniciada e lhe permitirá provisionar o novo pacote de conteúdo. Quando tiver feito isso com êxito, clique em \"Concluir\" abaixo para atualizar a lista de conteúdo alternativo. Caso tenha um erro ou opte por não instalar o pacote de conteúdo, clique em Cancelar, e você pode voltar a qualquer momento.",
    AdminCdnCompleteButton: "Concluído",
    AdminCdnCancelButton: "Cancelar",
    AdminCdnSaveButton: "Salvar",
    AdminCdnUpdateButton: "Atualizar",
    AdminRemoveCdn: "Confirme se deseja remover a CDN selecionada?",
    AdminAbout: "Sobre Web Part",
    DocumentationLinkLabel: "Abrir documentação de caminho de aprendizagem M365",
    CategoryCopyPlaylistFail: "Falha ao copiar playlist. Contate o administrador ou confira o console do navegador para obter mais detalhes.",
    PlaylistEditCopyLabel: "Copiar playlist",
    PlaylistNext: "Próximo",
    PlaylistPrevious: "Anterior",
    PlaylistFullScreen: "Entrar no modo de exibição de tela inteira",
    FilterNotSet: "Todos",
    AdminVersionUpdateNotice: "A Web Part de caminhos de aprendizagem do Microsoft 365 instalado está desatualizada. Você está executando a versão %0% e a versão mais recente é %1%.",
    AdminVersionUpdateInstructions: "Confira as instruções em \"Atualizando a solução\".",
    AdminSecurityMessage: "Você não tem direitos para administrar os caminhos de aprendizagem do Microsoft 365. Converse com o administrador sobre como ingressar no grupo de proprietários ou de membros.",
    AdminConfigIssueMessage: "Os caminhos de aprendizagem do Microsoft 365 têm um problema de configuração. Contate o administrador para obter ajuda. [Administradores: Para obter detalhes dos logs, confira o console do navegador. Para assistência técnica, confira a lista de problemas em https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "Url: Aguardando o título...",
    CreatingPage: "Criando página",
    TryAgain: "Tentar novamente",
    AddLanguagePlaceholder: "Adicionar idioma",
    NotApplicable: "Não aplicável",
    DataUpgradeTitle: "Atualização de dados de",
    DataUpgradeIntro: "Você atualizou para uma nova versão dos caminhos de aprendizagem do Microsoft 365. Para iniciar o processo de atualização, pressione \"Iniciar\"",
    DataUpgradeStart: "Início",
    DataUpgradeClose: "Fechar",
    DataUpgradeIssue: "Se você encontrar problemas ao executar a atualização, poderá solicitar assistência enviando um problema à ",
    DataUpgradeIssueLink: "lista de problemas do GitHub dos caminhos de aprendizado do Microsoft 365.",
    DataUpgradeLog: "Atualizar o log",
    DataUpgradeComplete: "A atualização foi concluída.",
    DataUpgradeErrors: "Erros",
    LogLevel: "Nível",
    LogMessage: "Mensagem",
    AboutGroupHeader: "Caminhos de aprendizado do M365",
    AboutGroupTitle: "Configuração atual*",
    AboutGroupTitle2: "(* será o pacote de conteúdo atual)",
    AboutLearningSiteUrl: "URL do site de aprendizagem:",
    AboutBaseCDNPath: "Caminho da CDN base:",
    AboutTelemetryStatus: "Status de telemetria:",
    AboutCurrentWPVersion: "Versão da Web Part atual:",
    AboutMultilingualEnabled: "Páginas Multilíngues Habilitadas:",
    AboutMultilingualLanguages: "Idiomas de Tradução de Páginas Multilíngues:",
    AboutConfiguredLanguages: "Idiomas Configurados:",
    AboutSupportedLanguages: "Idiomas com suporte para o pacote de conteúdo:",
    AboutDefaultSiteLanguage: "Idioma padrão do site:",
    AboutCurrentUserLanguage: "Idioma do usuário atual:",
    AboutContentPackAssetOrigins: "Origens do ativo do pacote de conteúdo:",
    AboutCurrentCDN: "CDN atual:",
    AboutAllCDNs: "Todos os CDNs:",
    AboutCacheLastUpdate: "Última atualização do cache:",
    DocumentLibraries: "Bibliotecas de documentos",
    OpenButtonLabel: "Abrir",
    CancelButtonLabel: "Cancelar",
    UploadFileHeader: "Carregar arquivo",
    ChangeFileLinkLabel: "Alterar arquivo",
    ChooseFileLinkLabel: "Escolher Arquivo",
    AddFileButtonLabel: "Adicionar arquivo",
    WebSearchLinkLabel: "Pesquisa na Web",
    CreativeCommonsMessage: "Esses resultados são marcados com licenças Creative Commons. Examine as licenças para garantir que você esteja em conformidade.",
    CopyrightWarning: "Você é responsável por respeitar os direitos de outras pessoas, incluindo os direitos autorais.",
    CopyrightUrl: "https://www.microsoft.com/pt-BR/legal/copyright/default.aspx",
    LearnMoreLink: "Saiba mais.",
    NoResultsBadEnglish: "***Nenhum resultado encontrado. Experimente alterar as opções de filtro",
    SearchResultAlt: "Resultado da imagem para {0}.",
    SearchResultAriaLabel: "Pressione Enter para abrir a fonte da imagem em uma nova guia.",
    SearchBoxPlaceholder: "Pesquisa na Web",
    PoweredByBing: "Da Plataforma Bing",
    SizeOptionAll: "Todos",
    SizeOptionExtraLarge: "Extra grande",
    SizeOptionLarge: "Grande",
    SizeOptionMedium: "Médio",
    SizeOptionSmall: "Pequeno",
    LayoutOptionAll: "Todos",
    LayoutOptionSquare: "Quadrado",
    LayoutOptionTall: "Alto",
    LayoutOptionWide: "Largo",
    LicenseOptionAll: "Todos",
    LicenseOptionAny: "Creative Commons apenas",
    RecentDocumentsHeader: "Documentos recentes",
    Loading: "Carregando...",
    NoRecentFiles: "Nenhum arquivo recente",
    NoRecentFilesDescription: "Experimente selecionar um arquivo do seu site ou carregar um do seu dispositivo.",
    EditedByNamePlate: "editado por ",
    LinkHeader: "De um link",
    LinkFileInstructions: "Colar um link para um arquivo no OneDrive for Business ou no SharePoint Online",
    NoExternalLinksValidationMessage: "Só há suporte para vinculação de arquivos em sua própria organização.",
    ProvidedValueIsInvalid: "O valor fornecido é inválido",
    ImageAriaLabelTemplate: ".{0} Imagem",
    DocumentLabelTemplate: "{0}, documento, modificado {1}, editado por {2}, particular",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, pasta, modificado {1}, editado por {2}, {3} itens, particular",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 bytes",
    SizeUnit: [
      "bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "Seletor de arquivos",
    OrgAssetsTabLabel: "Arquivos e imagens fornecidos pela sua organização",
    RecentLinkLabel: "Recentes",
    SiteLinkLabel: "Site",
    UploadLinkLabel: "Carregar",
    FromLinkLinkLabel: "De um link",
    TypeAriaLabel: "Operações de coluna para tipo de arquivo, pressione para classificar por tipo de arquivo",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Pasta",
    ImageAltText: ".{0} Imagem",
    NameField: "Nome",
    SortedAscending: "Classificados de A a Z",
    SortedDescending: "Classificados de Z a A",
    ModifiedField: "Data de modificação",
    ModifiedByField: "Modificado por",
    FileSizeField: "Tamanho do arquivo",
    OneDriveEmptyFolderAlt: "Esvaziar pasta",
    OneDriveEmptyFolderDescription: "Para adicionar arquivos, vá para o OneDrive. Você também pode adicionar arquivos a essa pasta usando o aplicativo OneDrive do seu computador.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Esta pasta está vazia",
    ListLayoutAriaLabel: "Visualizar opções. {0} {1}.",
    ListLayoutCompact: "Visualização compacta",
    ListLayoutCompactDescription: "Exibir itens e detalhes em uma lista compacta",
    ListLayoutList: "Modo de exibição de lista",
    ListLayoutListDescription: "Exibir itens e detalhes em uma lista",
    ListLayoutTile: "Exibição lado a lado",
    ListLayoutTileDescription: "Exibir itens com visualizações de blocos",
    ListOptionsAlt: "Visualizar opções. {0} selecionado .",
    ListOptionsTitle: "Abrir o menu de opções de visualização",
    Selected: "selecionado",
    CategoryTranslationNotAvailable: "Uma tradução da subcategoria selecionada não está disponível para esse idioma.",
    Abandoned: "Descartado",
    AbandonedPlaylist: "Playlists",
    RemoveLanguageLabel: "Remover idioma",
    PropertyPaneNone: "nenhum",
    WebPartModeFull: "Completo",
    WebPartModeContentOnly: "Apenas conteúdo",
    PropertyPaneFilterCategory: "Categoria",
    PropertyPaneFilterSubCategory: "Subcategoria",
    PropertyPaneFilterPlaylist: "Playlist",
    AdminSavingNotification: "Salvando...",
    DataUpgradeReview: "Revisão",
    DataUpgradeMultilingual: "O suporte multilíngue está ativado para os caminhos de aprendizado. Revise os idiomas habilitados para o seu site e desabilite os idiomas que você não quer oferecer suporte.",
    M365Title: "Caminhos de aprendizado do Microsoft 365",
    ValidateBase: "The base url for the CDN must end in a (/).",
    CustomizeSort: "Customize Sort",
    ResetSort: "Reset Sort"
  };
});