declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Название веб-части (только для контента)",
    LPViewerPropertyDescription: "Пользовательские свойства обучения",
    LPViewerPropertyGroupName: "Режим по умолчанию",
    WebpartModeLabel: "Выбор режима веб-части",
    WebpartModeDescription: "Как вы хотите отобразить веб-часть",
    ShowNavigationLabel: "Показать пользовательский учебный заголовок навигации",
    DefaultFilterLabel: "Выберите фильтр",
    DefaultFilterDescription: "Выберите фильтр, чтобы ограничить результаты. Вы можете фильтровать только по одному типу за раз.",
    DefaultCategoryLabel: "Фильтр по категории",
    DefaultCategoryDescription: "Выберите категорию, чтобы ограничить результаты.",
    DefaultSubCategoryLabel: "Фильтровать в подкатегорию",
    DefaultSubCategoryDescription: "Выберите подкатегорию, чтобы ограничить результаты.",
    DefaultPlaylistLabel: "Фильтр в плейлист",
    DefaultPlaylistDescription: "Выберите категорию, чтобы ограничить результаты.",
    DefaultAssetLabel: "Выберите Актив",
    DefaultAssetDescription: "Выберите актив для отображения из списка воспроизведения.",
    FilterPanelHeader: "Выберите курсы, которые подходят вам лучше всего",
    FilterPanelAudienceLabel: "Я",
    FilterPanelSkillsetLabel: "Мой уровень навыков",
    NavigationHome: "Главная",
    SearchResultItemPlayListLabel: "Плейлист: ",
    SearchResultItemCategoryLabel: "Категория: ",
    SearchPanelPlaceHolderLabel: "Поиск плейлистов или активов",
    LinkPanelCopyLabel: "Копировать",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Текущий плейлист: ",
    HeaderPlaylistPanelAdminHeader: "Администрирование",
    PlaylistOverviewDesignMessage: "Во время использования эта область будет отображать другие ресурсы в списке воспроизведения, в котором она отображается.",
    PlaylistOverviewHeading: "Все шаги в плейлисте",
    BurgerButton: "Бургер",
    LinkButton: "Ссылка",
    SearchButton: "Поиск",
    AdministerPlaylist: "Администрирование плейлистов",
    NoSearchResults: "Результаты поиска не соответствуют вашему запросу.",
    DefaultCDNLabel: "Выберите источник обучения",
    DefaultCDNDescription: "Выберите альтернативный источник для учебного контента.",
    DescriptionFieldLabel: "Поле описания",
    ImageSelectorLabel: "Выберите изображение",
    ImageSelectorButton: "Выберите изображение",
    DetailEditTitle: "Должность",
    DetailEditDescription: "Описание",
    DetailEditUrl: "Url",
    DetailEditCategory: "Категория",
    DetailEditCategoryNoData: "Нет доступных категорий",
    DetailEditTechnology: "Технологии",
    DetailEditLevel: "Уровень",
    DetailEditAudience: "Аудитория",
    AssetSearchPlaceHolderLabel: "Поиск существующих активов",
    CategoryHeading: "Добавить новую подкатегорию",
    CategoryHeadingLabel: "Подкатегория",
    CategoryPlaylistSavedMessage: "Плейлист был сохранен!",
    CategoryPlaylistSaveFailedMessage: "Не удалось сохранить плейлист!",
    CategoryNewPlayListMessage: "Вы внесли изменения в новый плейлист. Хотите отменить изменения и продолжить?",
    CategoryEditedPlayListMessage: "Вы внесли изменения в этот плейлист. Хотите отменить изменения и продолжить?",
    PlaylistEditAssetSavedMessage: "Актив был сохранен!",
    PlaylistEditAssetSaveFailedMessage: "Не удалось сохранить актив!",
    PlaylistEditCreatePlaylistHeader: "Создать новый плейлист",
    PlaylistEditPlaylistDetailsHeader: "Детали плейлиста: ",
    PlaylistEditPlaylistAssetsHeader: "Активы плейлиста",
    PlaylistEditEditLabel: "Редактировать детали",
    PlaylistEditSaveLabel: "Сохранить детали",
    PlaylistEditCancelLabel: "Отмена детали",
    PlaylistEditCloseLabel: "Закрыть плейлист",
    AssetDetailsCreateHeader: "Создать новый актив",
    AssetDetailsManageHeader: "Управление пользовательским активом:",
    AssetDetailsDetailsHeader: "Детали актива: ",
    AssetDetailsSaveLabel: "Сохранить Актив",
    AssetDetailsCancelLabel: "Отменить Актив",
    AssetDetailsCloseLabel: "Закрыть актив",
    AssetDetailsOpenPage: "Открыть страницу",
    TechnologyHeadingLabel: "Технологии",
    SubcategoryHeadingLabel: "Заголовок подкатегории",
    PlaylistItemPlaylistHeadingLabel: "Плейлист",
    PlaylistItemPlaylistDelete: "Удалить плейлист",
    PlaylistEditAssetNewLabel: "Новое основное средство",
    PlaylistRemove: "Удалить из плейлиста",
    ImageSelectorImageAlt: "Пользовательский плейлист",
    ImageSelectorUrlPlaceholder: "URL изображения",
    CategoryHeadingAddPlaylistToSubcategory: "Добавить новый плейлист в подкатегорию",
    AdminMenuTechnologyLabel: "Технологии",
    AdminMenuCategoryLabel: "Категория",
    Show: "Показать",
    Hide: "Скрыть",
    Add: "Добавить",
    Edit: "Изменить",
    CloseButton: "Закрыть",
    EditButton: "Изменить",
    StepButton: "Шаг",
    MoveUpButton: "Вверх",
    MoveDownButton: "Вниз",
    SaveButton: "Сохранить",
    CancelButton: "Отмена",
    UpdateButton: "Обновление",
    DeleteButton: "Удалить",
    DetailEditNewPageMessage: "Новая страница ресурсов в библиотеке страниц сайта.",
    DetailEditExistingPageMessage: "Введите URL-адрес существующей страницы.",
    DetailEditNewPageButton: "Создать страницу актива",
    DetailEditExistingPageButton: "Введите URL",
    AdminAddCdnLabel: "Добавить пакет содержимого",
    AdminEditCdnLabel: "Редактировать пакет материалов",
    AdminDeleteCdnLabel: "Удалить пакет содержимого",
    AdminCdnIdLabel: "Идентификатор пакета содержимого / идентификатор партнера",
    AdminCdnDisplayName: "Отображаемое имя",
    AdminCdnBaseUrl: "Базовый URL-адрес",
    AdminCustomCdnTitle: "Пакет пользовательских материалов",
    AdminCustomCdnDescription: "Пользовательские пакеты содержимого являются расширенной функцией и должны использоваться только администраторами с опытом администрирования веб-содержимого. Ненадежные источники контента могут вводить небезопасный контент на ваш сайт. Вы должны только добавить источники, которым вы доверяете. Для получения дополнительной информации см. Руководство для партнеров в документации по путям обучения.",
    AdminConfirmContentPack: "Запущена новая вкладка браузера, которая позволит вам подготовить новый пакет контента. После успешного завершения нажмите «Завершить» ниже, чтобы обновить список альтернативного содержимого. Если у вас есть ошибка или вы не хотите устанавливать пакет содержимого, пожалуйста, нажмите «Отмена», вы можете вернуться в любое время.",
    AdminCdnCompleteButton: "Завершено",
    AdminCdnCancelButton: "Отмена",
    AdminCdnSaveButton: "Сохранить",
    AdminCdnUpdateButton: "Обновление",
    AdminRemoveCdn: "Пожалуйста, подтвердите, что вы хотите удалить выбранный CDN?",
    AdminAbout: "О веб-части",
    DocumentationLinkLabel: "Открыть документацию по путям обучения M365",
    CategoryCopyPlaylistFail: "Не удалось скопировать плейлист, пожалуйста, свяжитесь с администратором или посмотрите консоль браузера для более подробной информации.",
    PlaylistEditCopyLabel: "Копировать плейлист",
    PlaylistNext: "Далее",
    PlaylistPrevious: "Назад",
    PlaylistFullScreen: "Переключить полноэкранный режим",
    FilterNotSet: "Все",
    AdminVersionUpdateNotice: "Ваша установленная веб-часть Microsoft 365 «Пути обучения» устарела. В настоящий момент используется версия %0%, а последняя версия — %1%.",
    AdminVersionUpdateInstructions: "Ознакомьтесь с инструкциями для «Обновления решения».",
    AdminSecurityMessage: "У вас нет прав на администрирование путей обучения Microsoft 365. Пожалуйста, обратитесь к администратору для включения в группу владельцев или участников",
    AdminConfigIssueMessage: "У путей обучения Microsoft 365 есть проблема конфигурации. Обратитесь к администратору за помощью. [Администраторы: Пожалуйста, смотрите консоль браузера для подробных журналов. Для получения технической помощи ознакомьтесь со списком вопросов по адресу https://github.com/pnp/custom-learning-office-365/issues.]",
    AdminAwaitingUrlPrompt: "Url: В ожидании заголовка...",
    CreatingPage: "Создание страницы",
    TryAgain: "Попробуйте еще раз.",
    AddLanguagePlaceholder: "Добавление языка",
    NotApplicable: "Неприменимо",
    DataUpgradeTitle: "Обновление данных с",
    DataUpgradeIntro: "Вы обновились до новой версии путей обучения Microsoft 365. Чтобы начать процесс обновления, нажмите «Пуск»",
    DataUpgradeStart: "Начало",
    DataUpgradeClose: "Закрыть",
    DataUpgradeIssue: "Если у вас возникли проблемы с обновлением, вы можете запросить помощь, отправив вопрос в ",
    DataUpgradeIssueLink: "Список вопросов GitHub по схемам обучения Microsoft 365",
    DataUpgradeLog: "Обновление журнала",
    DataUpgradeComplete: "Обновление завершено.",
    DataUpgradeErrors: "Ошибки",
    LogLevel: "Уровень",
    LogMessage: "Сообщение",
    AboutGroupHeader: "M365 пути обучения",
    AboutGroupTitle: "Текущая конфигурация*",
    AboutGroupTitle2: "(* будет зависеть от текущего пакета содержимого)",
    AboutLearningSiteUrl: "URL сайта обучения:",
    AboutBaseCDNPath: "Базовый путь CDN:",
    AboutTelemetryStatus: "Статус телеметрии:",
    AboutCurrentWPVersion: "Текущая версия веб-части:",
    AboutMultilingualEnabled: "Страницы с текстом на нескольких языках включены:",
    AboutMultilingualLanguages: "Языки для перевода страниц с текстом на нескольких языках:",
    AboutConfiguredLanguages: "Настроенные языки:",
    AboutSupportedLanguages: "Content Pack Поддерживаемые языки:",
    AboutDefaultSiteLanguage: "Язык сайта по умолчанию:",
    AboutCurrentUserLanguage: "Текущий язык пользователя:",
    AboutContentPackAssetOrigins: "Источники активов пакета содержимого:",
    AboutCurrentCDN: "Текущий CDN:",
    AboutAllCDNs: "Все CDN:",
    AboutCacheLastUpdate: "Последнее обновление кэша:",
    DocumentLibraries: "Библиотеки документов",
    OpenButtonLabel: "Открыть",
    CancelButtonLabel: "Отмена",
    UploadFileHeader: "Загрузить файл",
    ChangeFileLinkLabel: "Изменить файл",
    ChooseFileLinkLabel: "Выберите файл",
    AddFileButtonLabel: "Добавить файл",
    WebSearchLinkLabel: "поиск в интернете",
    CreativeCommonsMessage: "Эти результаты помечены лицензиями Creative Commons. Просмотрите лицензии, чтобы убедиться, что вы соответствуете.",
    CopyrightWarning: "Вы несете ответственность за уважение прав других людей, в том числе авторского права.",
    CopyrightUrl: "https://www.microsoft.com/ru-RU/legal/copyright/default.aspx",
    LearnMoreLink: "Подробнее.",
    NoResultsBadEnglish: "***Не найдено ни одного результата. Попробуйте изменить параметры фильтра",
    SearchResultAlt: "Результат изображения для {0}.",
    SearchResultAriaLabel: "Нажмите ввод, чтобы открыть источник изображения в новой вкладке.",
    SearchBoxPlaceholder: "поиск в интернете",
    PoweredByBing: "На платформе Bing",
    SizeOptionAll: "Все",
    SizeOptionExtraLarge: "Очень большой",
    SizeOptionLarge: "Большой",
    SizeOptionMedium: "Средняя",
    SizeOptionSmall: "Малый",
    LayoutOptionAll: "Все",
    LayoutOptionSquare: "Квадратный",
    LayoutOptionTall: "Высокий",
    LayoutOptionWide: "Широкие",
    LicenseOptionAll: "Все",
    LicenseOptionAny: "Только Creative Commons",
    RecentDocumentsHeader: "Последние документы",
    Loading: "Идет загрузка...",
    NoRecentFiles: "Нет последних файлов",
    NoRecentFilesDescription: "Попробуйте выбрать файл со своего сайта или загрузить его со своего устройства.",
    EditedByNamePlate: "Отредактировано ",
    LinkHeader: "По ссылке",
    LinkFileInstructions: "Вставьте ссылку на файл в OneDrive для бизнеса или SharePoint Online",
    NoExternalLinksValidationMessage: "Мы поддерживаем только ссылки на файлы в вашей собственной организации.",
    ProvidedValueIsInvalid: "Предоставленное значение недействительно",
    ImageAriaLabelTemplate: ".{0} Изображение",
    DocumentLabelTemplate: "{0}, документ, измененный \\ {1\\}, отредактированный \\ {2\\}, частный",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, Папка, Изменено \\ {1\\}, отредактировано \\ {2\\}, \\ {3\\} элементами, Частное",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 байт",
    SizeUnit: [
      "В байтах",
      "КБ",
      "MB",
      "ГБ",
      "ТБ",
      "ПБ",
      "ЕБ",
      "ЗБ",
      "ИБ"
    ],
    FilePickerHeader: "Средство выбора файлов",
    OrgAssetsTabLabel: "Изображения и файлы, предоставленные вашей организацией",
    RecentLinkLabel: "Последние",
    SiteLinkLabel: "Сайт",
    UploadLinkLabel: "Отправка",
    FromLinkLinkLabel: "По ссылке",
    TypeAriaLabel: "Операции с колонками для типа файла, нажмите для сортировки по типу файла",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Папка",
    ImageAltText: ".{0} Изображение",
    NameField: "Имя",
    SortedAscending: "Сортировка от а до я",
    SortedDescending: "Сортировка от я до а",
    ModifiedField: "Дата изменения",
    ModifiedByField: "Кем изменено",
    FileSizeField: "Размер файла",
    OneDriveEmptyFolderAlt: "Очистить папку",
    OneDriveEmptyFolderDescription: "Чтобы добавить файлы, перейдите на свой OneDrive. Вы также можете добавить файлы в эту папку, используя приложение OneDrive для вашего компьютера.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Эта папка пуста",
    ListLayoutAriaLabel: "Просмотр вариантов. {0}  {1} .",
    ListLayoutCompact: "Компактное представление",
    ListLayoutCompactDescription: "Просмотр предметов и деталей в компактном списке",
    ListLayoutList: "Представление списка",
    ListLayoutListDescription: "Просмотр предметов и деталей в списке",
    ListLayoutTile: "Вид плитки",
    ListLayoutTileDescription: "Просмотр элементов с предварительным просмотром плитки",
    ListOptionsAlt: "Просмотр вариантов. {0} выбрано.",
    ListOptionsTitle: "Открыть меню вариантов просмотра",
    Selected: "выбранный",
    CategoryTranslationNotAvailable: "Перевод выбранной подкатегории недоступен для этого языка.",
    Abandoned: "заброшенный",
    AbandonedPlaylist: "Плейлисты",
    RemoveLanguageLabel: "Удалить язык",
    PropertyPaneNone: "нет",
    WebPartModeFull: "Полный",
    WebPartModeContentOnly: "Только содержимое",
    PropertyPaneFilterCategory: "Категория",
    PropertyPaneFilterSubCategory: "Подкатегория",
    PropertyPaneFilterPlaylist: "Плейлист",
    AdminSavingNotification: "Сохранение...",
    DataUpgradeReview: "Просмотр",
    DataUpgradeMultilingual: "Многоязыковая поддержка включена для схем обучения. Просмотрите языки, поддерживаемые сайтом, и отключите те, которые не требуются.",
    M365Title: "Схемы обучения Microsoft 365",
    ValidateBase: "The base url for the CDN must end in a (/).",
    CustomizeSort: "Customize Sort",
    ResetSort: "Reset Sort"
  };
});