declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Web 部件标题（仅内容模式）",
    LPViewerPropertyDescription: "自定义学习属性",
    LPViewerPropertyGroupName: "默认视图",
    WebpartModeLabel: "选择 Web 部件模式",
    WebpartModeDescription: "你想要如何显示 Web 部件",
    ShowNavigationLabel: "显示自定义学习导航标题",
    DefaultFilterLabel: "选择筛选器",
    DefaultFilterDescription: "选择筛选器以限制结果。一次只能通过一个类型进行筛选。",
    DefaultCategoryLabel: "筛选到类别",
    DefaultCategoryDescription: "选择一个类别以限制结果。",
    DefaultSubCategoryLabel: "筛选到子类别",
    DefaultSubCategoryDescription: "选择一个子类别以限制结果。",
    DefaultPlaylistLabel: "筛选到播放列表",
    DefaultPlaylistDescription: "选择一个类别以限制结果。",
    DefaultAssetLabel: "选择一个资产",
    DefaultAssetDescription: "从播放列表中选择要显示的资产。",
    FilterPanelHeader: "选择最适合你的课程",
    FilterPanelAudienceLabel: "我是一名",
    FilterPanelSkillsetLabel: "我的技能集是",
    NavigationHome: "主页",
    SearchResultItemPlayListLabel: "播放列表：",
    SearchResultItemCategoryLabel: "类别：",
    SearchPanelPlaceHolderLabel: "搜索播放列表或资产",
    LinkPanelCopyLabel: "复制",
    HeaderPlaylistPanelCurrentPlaylistLabel: "当前播放列表：",
    HeaderPlaylistPanelAdminHeader: "管理",
    PlaylistOverviewDesignMessage: "在使用期间，此区域将显示该资产所在播放列表中的其他资产。",
    PlaylistOverviewHeading: "播放列表中的所有步骤",
    BurgerButton: "汉堡",
    LinkButton: "链接",
    SearchButton: "搜索",
    AdministerPlaylist: "播放列表管理",
    NoSearchResults: "没有符合查询条件的搜索结果。",
    DefaultCDNLabel: "选择学习来源",
    DefaultCDNDescription: "选择备用学习内容来源。",
    DescriptionFieldLabel: "说明字段",
    ImageSelectorLabel: "选择图像",
    ImageSelectorButton: "选择图像",
    DetailEditTitle: "标题",
    DetailEditDescription: "说明",
    DetailEditUrl: "URL",
    DetailEditCategory: "类别",
    DetailEditCategoryNoData: "无可用类别",
    DetailEditTechnology: "技术",
    DetailEditLevel: "级别",
    DetailEditAudience: "受众",
    AssetSearchPlaceHolderLabel: "搜索现有资产",
    CategoryHeading: "添加新子类别",
    CategoryHeadingLabel: "子类别",
    CategoryPlaylistSavedMessage: "已保存播放列表！",
    CategoryPlaylistSaveFailedMessage: "无法保存播放列表！",
    CategoryNewPlayListMessage: "已对新播放列表进行更改。想要放弃所做的更改并继续吗？",
    CategoryEditedPlayListMessage: "已对此播放列表进行更改。想要放弃所做的更改并继续吗？",
    PlaylistEditAssetSavedMessage: "已保存资产！",
    PlaylistEditAssetSaveFailedMessage: "无法保存资产！",
    PlaylistEditCreatePlaylistHeader: "创建新播放列表",
    PlaylistEditPlaylistDetailsHeader: "播放列表详细信息：",
    PlaylistEditPlaylistAssetsHeader: "播放列表资产",
    PlaylistEditEditLabel: "编辑详细信息",
    PlaylistEditSaveLabel: "保存详细信息",
    PlaylistEditCancelLabel: "取消详细信息",
    PlaylistEditCloseLabel: "关闭播放列表",
    AssetDetailsCreateHeader: "创建新资产",
    AssetDetailsManageHeader: "管理自定义资产：",
    AssetDetailsDetailsHeader: "资产详细信息：",
    AssetDetailsSaveLabel: "保存资产",
    AssetDetailsCancelLabel: "取消资产",
    AssetDetailsCloseLabel: "关闭资产",
    AssetDetailsOpenPage: "打开页面",
    TechnologyHeadingLabel: "技术",
    SubcategoryHeadingLabel: "子类别标题",
    PlaylistItemPlaylistHeadingLabel: "播放列表",
    PlaylistItemPlaylistDelete: "删除播放列表",
    PlaylistEditAssetNewLabel: "新建资产",
    PlaylistRemove: "从播放列表中删除",
    ImageSelectorImageAlt: "自定义播放列表",
    ImageSelectorUrlPlaceholder: "图像 URL",
    CategoryHeadingAddPlaylistToSubcategory: "向子类别添加新的播放列表",
    AdminMenuTechnologyLabel: "技术",
    AdminMenuCategoryLabel: "类别",
    Show: "显示",
    Hide: "隐藏",
    Add: "添加",
    Edit: "编辑",
    CloseButton: "关闭",
    EditButton: "编辑",
    StepButton: "步骤",
    MoveUpButton: "上移",
    MoveDownButton: "下移",
    SaveButton: "保存",
    CancelButton: "取消",
    UpdateButton: "更新",
    DeleteButton: "删除",
    DetailEditNewPageMessage: "“网站页面”库中的新资产页面。",
    DetailEditExistingPageMessage: "输入现有页面的 URL。",
    DetailEditNewPageButton: "创建资产页面",
    DetailEditExistingPageButton: "输入 URL",
    AdminAddCdnLabel: "添加内容包",
    AdminEditCdnLabel: "编辑内容包",
    AdminDeleteCdnLabel: "删除内容包",
    AdminCdnIdLabel: "内容包 ID/合作伙伴 ID",
    AdminCdnDisplayName: "显示名称",
    AdminCdnBaseUrl: "基 URL",
    AdminCustomCdnTitle: "自定义内容包",
    AdminCustomCdnDescription: "自定义内容包是一项高级功能，应仅由具有 Web 内容管理经验的管理员使用。不可靠的内容源可能会将不安全的内容引入你的网站。请仅添加你信任的源。有关详细信息，请参阅学习路径文档中的“合作伙伴指南”。",
    AdminConfirmContentPack: "已启动新的浏览器选项卡，你可以预配新的内容包。成功完成此操作后，请单击下面的“完成”以更新备用内容列表。如果出现错误或选择不安装内容包，请单击“取消”，你随时可以返回。",
    AdminCdnCompleteButton: "完成",
    AdminCdnCancelButton: "取消",
    AdminCdnSaveButton: "保存",
    AdminCdnUpdateButton: "更新",
    AdminRemoveCdn: "请确认是否要删除选定的 CDN？",
    AdminAbout: "关于 Web 部件",
    DocumentationLinkLabel: "打开 M365 学习路径文档",
    CategoryCopyPlaylistFail: "复制播放列表失败，请与管理员联系或查看浏览器控制台以了解更多详细信息。",
    PlaylistEditCopyLabel: "复制播放列表",
    PlaylistNext: "下一步",
    PlaylistPrevious: "上一步",
    PlaylistFullScreen: "切换全屏模式",
    FilterNotSet: "全部",
    AdminVersionUpdateNotice: "你安装的 Microsoft 365 学习路径 Web 部件已过期。你现在运行的是 %0% 版本，最新版本是 %1%。",
    AdminVersionUpdateInstructions: "请查看有关“更新解决方案”的说明。",
    AdminSecurityMessage: "你不具有管理 Microsoft 365 学习路径的权限。请与管理员联系，以便加入“所有者”或“成员”组。",
    AdminConfigIssueMessage: "Microsoft 365 学习路径存在配置问题。请向管理员寻求帮助。[管理员：有关详细日志，请参阅浏览器控制台。如需技术援助，请查看 https://github.com/pnp/custom-learning-office-365/issues 中的问题列表。]",
    AdminAwaitingUrlPrompt: "URL：正在等待标题...",
    CreatingPage: "创建页面",
    TryAgain: "请重试",
    AddLanguagePlaceholder: "添加语言",
    NotApplicable: "不适用",
    DataUpgradeTitle: "从以下对象进行的数据升级",
    DataUpgradeIntro: "你已更新至 Microsoft 365 学习路径的主要新版本。若要开始升级过程，请按“开始”",
    DataUpgradeStart: "开始",
    DataUpgradeClose: "关闭",
    DataUpgradeIssue: "如果在执行更新时遇到问题，可通过将问题提交到 ",
    DataUpgradeIssueLink: "Microsoft 365 学习路径 GitHub 问题列表，请求获得帮助。",
    DataUpgradeLog: "升级日志",
    DataUpgradeComplete: "已完成升级。",
    DataUpgradeErrors: "错误",
    LogLevel: "级别",
    LogMessage: "消息",
    AboutGroupHeader: "M365 学习路径",
    AboutGroupTitle: "当前配置*",
    AboutGroupTitle2: "（* 将专门针对当前内容包）",
    AboutLearningSiteUrl: "学习网站 URL：",
    AboutBaseCDNPath: "基 CDN 路径：",
    AboutTelemetryStatus: "遥测状态：",
    AboutCurrentWPVersion: "当前 Web 部件版本：",
    AboutMultilingualEnabled: "已启用多语言页面：",
    AboutMultilingualLanguages: "多语言页面的翻译语言：",
    AboutConfiguredLanguages: "配置的语言：",
    AboutSupportedLanguages: "内容包支持的语言：",
    AboutDefaultSiteLanguage: "默认网站语言：",
    AboutCurrentUserLanguage: "当前用户语言：",
    AboutContentPackAssetOrigins: "内容包资产来源：",
    AboutCurrentCDN: "当前 CDN：",
    AboutAllCDNs: "所有 CDN：",
    AboutCacheLastUpdate: "缓存上次更新：",
    DocumentLibraries: "文档库",
    OpenButtonLabel: "打开",
    CancelButtonLabel: "取消",
    UploadFileHeader: "上传文件",
    ChangeFileLinkLabel: "更改文件",
    ChooseFileLinkLabel: "选择文件",
    AddFileButtonLabel: "添加文件",
    WebSearchLinkLabel: "Web 搜索",
    CreativeCommonsMessage: "这些结果具有 Creative Commons 许可证标记。查看这些许可证，以确保合规。",
    CopyrightWarning: "你有责任尊重其他人的权利，包括版权。",
    CopyrightUrl: "https://www.microsoft.com/zh-CN/legal/copyright/default.aspx",
    LearnMoreLink: "了解更多。",
    NoResultsBadEnglish: "***未找到结果。尝试更改筛选器选项",
    SearchResultAlt: "{0} 的图像结果。",
    SearchResultAriaLabel: "按 Enter 即可在新选项卡中打开图像源。",
    SearchBoxPlaceholder: "Web 搜索",
    PoweredByBing: "由必应提供支持",
    SizeOptionAll: "全部",
    SizeOptionExtraLarge: "特大",
    SizeOptionLarge: "大型",
    SizeOptionMedium: "中型",
    SizeOptionSmall: "小型",
    LayoutOptionAll: "全部",
    LayoutOptionSquare: "正方形",
    LayoutOptionTall: "高",
    LayoutOptionWide: "宽",
    LicenseOptionAll: "全部",
    LicenseOptionAny: "仅限 Creative Commons",
    RecentDocumentsHeader: "最近使用的文档",
    Loading: "正在加载...",
    NoRecentFiles: "无最近使用的文件",
    NoRecentFilesDescription: "尝试从你的网站选择一个文件，或从你的设备上传一个。",
    EditedByNamePlate: "编辑者 ",
    LinkHeader: "来自链接",
    LinkFileInstructions: "将链接粘贴到 OneDrive for Business 或 SharePoint Online 中的文件",
    NoExternalLinksValidationMessage: "我们仅支持链接到你自己组织中的文件。",
    ProvidedValueIsInvalid: "提供的值无效",
    ImageAriaLabelTemplate: ".{0} 图像",
    DocumentLabelTemplate: "{0}，文档，修改时间 {1}，编辑者 {2}，私人",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}，文件夹，修改时间 {1}，编辑者 {2}，{3} 项，私人",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 字节",
    SizeUnit: [
      "字节",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "文件选取器",
    OrgAssetsTabLabel: "由你的组织提供的图像和文件",
    RecentLinkLabel: "最近使用",
    SiteLinkLabel: "网站",
    UploadLinkLabel: "上传",
    FromLinkLinkLabel: "来自链接",
    TypeAriaLabel: "针对“文件”类型的列操作，按下即可按文件类型排序",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "文件夹",
    ImageAltText: ".{0} 图像",
    NameField: "名称",
    SortedAscending: "按从 A 到 Z 排序",
    SortedDescending: "按从 Z 到 A 排序",
    ModifiedField: "修改日期",
    ModifiedByField: "修改者",
    FileSizeField: "文件大小",
    OneDriveEmptyFolderAlt: "空文件夹",
    OneDriveEmptyFolderDescription: "若要添加文件，请转到 OneDrive。你还可以使用你计算机的 OneDrive 应用将文件添加到此文件夹。",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "此文件夹为空",
    ListLayoutAriaLabel: "查看选项。{0} {1}。",
    ListLayoutCompact: "紧凑视图",
    ListLayoutCompactDescription: "在紧凑列表中查看项目和详细信息",
    ListLayoutList: "列表视图",
    ListLayoutListDescription: "在列表中查看项目和详细信息",
    ListLayoutTile: "磁贴视图",
    ListLayoutTileDescription: "使用磁贴预览查看项目",
    ListOptionsAlt: "视图选项。已选中 {0} 个。",
    ListOptionsTitle: "打开视图选项菜单",
    Selected: "已选中",
    CategoryTranslationNotAvailable: "所选子类别未提供此语言的翻译。",
    Abandoned: "已弃用",
    AbandonedPlaylist: "播放列表",
    RemoveLanguageLabel: "删除语言",
    PropertyPaneNone: "无",
    WebPartModeFull: "完整",
    WebPartModeContentOnly: "仅内容",
    PropertyPaneFilterCategory: "类别",
    PropertyPaneFilterSubCategory: "子类别",
    PropertyPaneFilterPlaylist: "播放列表",
    AdminSavingNotification: "正在保存...",
    DataUpgradeReview: "审阅",
    DataUpgradeMultilingual: "已针对学习路径启用多语言支持。请查看为你的网站启用的语言，并关闭你不想支持的语言。",
    M365Title: "Microsoft 365 学习路径",
    ValidateBase: "The base url for the CDN must end in a (/).",
    CustomizeSort: "Customize Sort",
    ResetSort: "Reset Sort"
  };
});